import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import NotFound from './NotFound'
import NeighborNav from './NeighborNav'
import SectionText from './SectionText'
import BillLinkify from './BillLinkify'
import { Breadcrumb, LoadingView, ErrorView } from './MuniCodeTitle'
import useDocumentTitle from '../hooks/useDocumentTitle'
import './MuniCodeDetail.css'

export default function MuniCodeSection() {
  const { title, chapter, section } = useParams()
  const fullSectionNumber = `${title}.${chapter}.${section}`

  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [status, setStatus] = useState(null)
  useDocumentTitle(data ? `SMC ${data.section_number}` : null)

  useEffect(() => {
    setData(null); setError(null); setStatus(null)
    fetch(`/api/smc/sections/${encodeURIComponent(fullSectionNumber)}/`)
      .then(r => {
        setStatus(r.status)
        if (r.status === 404) return null
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then(setData)
      .catch(e => setError(e.message))
  }, [fullSectionNumber])

  if (status === 404) return <NotFound />
  if (error) return <ErrorView msg={error} />
  if (!data) return <LoadingView />

  return (
    <div className="smc-detail-page">
      <div className="smc-detail-container">
        <Breadcrumb crumbs={[
          { to: '/', label: 'Home' },
          { to: '/municode', label: 'Municipal Code' },
          { to: `/municode/${data.title_number}`, label: `Title ${data.title_number}` },
          { to: `/municode/${data.title_number}/${data.chapter_number.split('.').slice(1).join('.')}`,
            label: `Chapter ${data.chapter_number}` },
          { current: data.section_number },
        ]} />

        <header className="smc-detail-header">
          <div className="smc-section-num">Section {data.section_number}</div>
          <h1 className="smc-detail-h1">{data.title}</h1>
          {data.chapter_name && (
            <p className="smc-detail-sub">
              Chapter {data.chapter_number} · {data.chapter_name}
            </p>
          )}
          {data.subchapter_roman && (
            <p className="smc-detail-sub">
              Subchapter {data.subchapter_roman}
              {data.subchapter_name ? ` — ${data.subchapter_name}` : ''}
            </p>
          )}
        </header>

        <div className={`smc-detail-content${data.plain_summary ? ' smc-detail-content--with-summary' : ''}`}>
          <section className="smc-section-body" aria-label="Section text">
            <SectionText text={data.full_text} billRefs={data.bill_refs} />
          </section>

          {data.plain_summary && (
            <aside className="smc-summary-panel" aria-label="Plain-language summary">
              <h2 className="smc-summary-heading">Plain-language summary</h2>
              {data.plain_summary.split('\n\n').map((para, i) => (
                <p key={i} className="smc-summary-body"><BillLinkify text={para} refs={data.bill_refs} /></p>
              ))}
              {data.summary_model && (
                <p className="smc-summary-meta">Generated by {data.summary_model}</p>
              )}
            </aside>
          )}
        </div>

        {data.source_pdf_page && (
          <p className="smc-source-note">
            Source: Seattle Municipal Code, PDF page {data.source_pdf_page}.
          </p>
        )}

        <NeighborNav neighbors={data.neighbors} ariaLabel="Section navigation" />
      </div>
    </div>
  )
}
