import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import NotFound from './NotFound'
import SectionText from './SectionText'
import { Breadcrumb, LoadingView, ErrorView } from './MuniCodeTitle'
import './MuniCodeDetail.css'

export default function MuniCodeSection() {
  const { title, chapter, section } = useParams()
  const fullSectionNumber = `${title}.${chapter}.${section}`

  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [status, setStatus] = useState(null)

  useEffect(() => {
    setData(null); setError(null); setStatus(null)
    fetch(`/api/smc/sections/${encodeURIComponent(fullSectionNumber)}/`)
      .then(r => {
        setStatus(r.status)
        if (r.status === 404) return null
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then(setData)
      .catch(e => setError(e.message))
  }, [fullSectionNumber])

  if (status === 404) return <NotFound />
  if (error) return <ErrorView msg={error} />
  if (!data) return <LoadingView />

  return (
    <main className="smc-detail-page">
      <div className="smc-detail-container">
        <Breadcrumb crumbs={[
          { to: '/', label: 'This Week' },
          { to: '/municode', label: 'Municipal Code' },
          { to: `/municode/${data.title_number}`, label: `Title ${data.title_number}` },
          { to: `/municode/${data.title_number}/${data.chapter_number.split('.').slice(1).join('.')}`,
            label: `Chapter ${data.chapter_number}` },
          { current: data.section_number },
        ]} />

        <header className="smc-detail-header">
          <div className="smc-section-num">{data.section_number}</div>
          <h1 className="smc-detail-h1">{data.title}</h1>
          {data.subchapter_roman && (
            <p className="smc-detail-sub">
              Subchapter {data.subchapter_roman}
              {data.subchapter_name ? ` — ${data.subchapter_name}` : ''}
            </p>
          )}
        </header>

        {/* Plain-language summary slot. The summarize_smc_sections command
            isn't built yet (see WORK_LOG); this panel hides until a row
            has plain_summary populated. */}
        {data.plain_summary && (
          <section className="smc-summary-panel" aria-label="Plain-language summary">
            <h2 className="smc-summary-heading">Plain-language summary</h2>
            <p className="smc-summary-body">{data.plain_summary}</p>
            {data.summary_model && (
              <p className="smc-summary-meta">Generated by {data.summary_model}</p>
            )}
          </section>
        )}

        <section className="smc-section-body" aria-label="Section text">
          <SectionText text={data.full_text} />
        </section>

        {data.source_pdf_page && (
          <p className="smc-source-note">
            Source: Seattle Municipal Code, PDF page {data.source_pdf_page}.
          </p>
        )}
      </div>
    </main>
  )
}
