"""Prompt + request construction for the digest intro batch (Phase 3, #238).

PII rule (plan §security 11): the request sent to Anthropic is built ONLY
from the whitelisted fields assembled here — issue-area tags, councilmember
names, the district label, bill identifiers, and the matched items' public
content. Never the subscriber's email, and the ``custom_id`` is the opaque
internal integer id. ``test_intro_prompt`` asserts no email-shaped string
survives into the serialized request body.
"""
import json

from django.conf import settings

from digests.services.llm_schema import compose_schema

# A short greeting paragraph + 2-4 bullet highlights, as JSON.
MAX_TOKENS = 500

# Style guide + few-shot exemplars. The exemplars were generated by the
# bootstrap (Opus) model over real preference profiles and curated by hand —
# see `manage.py bootstrap_digest_intros` — then tightened. Regenerate and
# re-curate them when the voice needs adjusting; don't hand-tune blind.
INTRO_SYSTEM_PROMPT = """\
You write the opening of a personalized email digest for Seattle \
Councilmatic, a nonpartisan civic-information site covering the Seattle \
City Council.

You receive JSON describing one subscriber's civic interests (issue areas, \
followed councilmembers, council district, followed bills) and the digest \
items matched to those interests this period — bills with recent council \
actions and committee-meeting recaps, each carrying the reason it matched \
("matched_because") and a short factual summary.

Voice: clear, direct, plainly written — a good local-news briefing. Second \
person where natural ("bills you follow"); contractions are fine. No \
bureaucratic stiffness, but no chumminess either: avoid folksy color \
("Busy week!", "plenty happening close to home"), figurative phrases \
("crossed the finish line"), and exclamations. No hype or advocacy; the \
substance stays strictly factual.

Return JSON with two keys:

"intro" — 1-2 sentences, at most 35 words, stating what happened this \
period across the subscriber's interest areas at a high level, e.g. \
"Council moved on housing density, homelessness response, and several \
City Light land transfers this week — most of it now signed or headed to \
full council." No bill identifiers here; the highlights carry those. \
Never open with throat-clearing like "This week's digest contains."

"highlights" — 2 to 4 strings, each a self-contained bullet of at most 22 \
words, each anchored on ONE concrete item: its identifier plus the single \
most newsworthy fact about it, preferring the newest development \
(latest_action — a vote, referral, signing) over a restated summary. Order \
by significance to this subscriber. Cover the digest's breadth rather than \
four variations on one theme; when more items exist than bullets, fold the \
leftovers into the last bullet ("…plus two more City Light property bills").

Hard rules for both keys:
- Attribute sponsorship and committee roles EXACTLY as the input states \
them: if a reason says "your district's councilmember" without naming \
anyone, use that phrase — never guess which named person it is, and never \
merge it with a followed councilmember's name.
- Councilmember framing comes from the input, never from inference. \
Reasons name each sponsoring member and mark the hat they wear — echo \
those framings: a member marked "your district's councilmember" may be \
described that way; members marked "(citywide)" serve the whole city, so \
refer to them by name alone. Never describe councilmembers collectively \
as "your councilmembers."
- Never say the subscriber "follows" specific bills — they can't. Items \
matched by tag are about "issues you follow"; sponsored items are from \
the named councilmember.
- State only facts present in the input. Never invent bill contents, \
votes, dates, or outcomes.
- Nonpartisan, no speculation about motives or outcomes.
- No greeting-card fluff ("Happy Friday!"), no sign-off, no mention of \
email mechanics (subscriptions, links, unsubscribing).

Examples follow. They describe OTHER subscribers' weeks — imitate the \
voice and structure, never reuse their facts.

Example input (abridged): {"subscriber_interests": {"issue_areas": ["Land \
Use & Zoning", "Utilities"]}, "items": [{"identifier": "CB 121196", \
"matched_because": ["Tagged Land Use & Zoning"], "latest_action": \
"Attested by City Clerk", "date": "2026-06-04", "summary": "Rezones \
parcels in Fremont, Downtown, the University District, Madison/Miller, and \
Rainier Beach… the City estimates 3,000-4,000 new homes over the next \
decade."}, {"identifier": "CB 121190", "matched_because": ["Tagged \
Utilities"], "summary": "Updates the Stormwater Code…"}, {"identifier": \
"CB 121199", "matched_because": ["Tagged Utilities"], "summary": "Accepts \
City Light salmon-habitat properties…"}, {"identifier": "CB 121197", \
"matched_because": ["Tagged Land Use & Zoning"], "summary": "Imposes \
landmark controls on the Woodin House…"}]}
Example output: {"intro": "The council finalized its citywide rezoning \
push this week and moved on stormwater rules and a pair of City Light \
land measures — all areas you follow.", "highlights": ["CB 121196, \
rezoning five neighborhoods with an estimated 3,000-4,000 new homes over \
the next decade, was attested June 4.", "CB 121190 updates Seattle's \
Stormwater Code.", "CB 121199 lets City Light accept salmon-habitat \
properties; also this week: landmark protections for the Woodin House \
(CB 121197)."]}

Example input (abridged): {"subscriber_interests": {"issue_areas": \
["Homelessness"], "district": "District 3"}, "items": [{"identifier": \
"Res 32202", "matched_because": ["Tagged Homelessness", "Sponsored by \
Alexis Mercedes Rinck (citywide)"], "latest_action": "Attested by City \
Clerk", "date": "2026-06-04", "summary": "Next steps after the forensic \
evaluation of the King County Regional Homelessness Authority…"}, \
{"identifier": "Res 32201", "matched_because": ["Sponsored by Joy \
Hollingsworth, your district's councilmember"], "latest_action": \
"Attested by City Clerk", "date": "2026-05-22", "summary": "Creates an \
Arts and Cultural District in Georgetown…"}]}
Example output: {"intro": "Movement this week on homelessness — one of \
the issues you follow — plus a new arts district from your district's \
councilmember.", "highlights": ["Res 32202, next steps after the King \
County Regional Homelessness Authority's forensic evaluation, was \
attested by the City Clerk June 4. Sponsored by Alexis Mercedes Rinck.", \
"Res 32201, creating a Georgetown Arts and Cultural District, was \
attested May 22. Sponsored by Joy Hollingsworth, your district's \
councilmember."]}\
"""


def build_intro_request(subscriber_id: int, prefs, items: list[dict],
                        cadence: str, model: str) -> dict:
    """One Anthropic Batch request for one subscriber's digest intro."""
    payload = {
        "cadence": cadence,
        "subscriber_interests": _prefs_context(prefs),
        "items": [_item_context(i) for i in items],
    }
    return {
        # Opaque internal id — matches Anthropic's ^[a-zA-Z0-9_-]{1,64}$
        # and carries no meaning outside our system.
        "custom_id": f"sub-{subscriber_id}",
        "params": {
            "model": model,
            "max_tokens": MAX_TOKENS,
            "system": [{
                "type": "text",
                "text": INTRO_SYSTEM_PROMPT,
                # Cached across the cohort inside each 5-minute window —
                # same idiom as summarize_legislation.
                "cache_control": {"type": "ephemeral"},
            }],
            "messages": [{
                "role": "user",
                "content": json.dumps(payload, ensure_ascii=False),
            }],
            "output_config": {
                "format": {
                    "type": "json_schema",
                    "schema": compose_schema(include_blurbs=False),
                },
            },
            # No `thinking`: the digest model is Haiku (which rejects the
            # parameter), and a 90-word intro doesn't warrant it anyway.
        },
    }


def _prefs_context(prefs) -> dict:
    """Whitelisted, PII-free view of the subscriber's preferences.

    No followed_bills key: the subscribe form can't create bill follows,
    and feeding the list would tempt the model into "bills you follow"
    phrasing the guide forbids. Legacy followed reps (also no longer
    collectable) still ride along with seat labels so old rows keep
    working."""
    return {
        "issue_areas": prefs.issue_areas,
        "followed_councilmembers": _followed_with_seats(prefs),
        "district": prefs.district.name if prefs.district else None,
    }


def _followed_with_seats(prefs) -> list[dict]:
    """Followed councilmembers with their council seat, so the model can
    tell a district representative from a citywide (Position) member —
    only the former is ever "your councilmember" in the subscriber's
    intro. Members without an active council seat get seat=None."""
    from datetime import date

    from django.db.models import Q

    from opencivicdata.core.models import Membership

    rep_ids = list(prefs.followed_reps.values_list("id", flat=True))
    seats: dict[str, str] = {}
    if rep_ids:
        memberships = Membership.objects.filter(
            person_id__in=rep_ids,
            organization__name="Seattle City Council",
        ).filter(
            Q(end_date="") | Q(end_date__gte=date.today().isoformat())
        ).exclude(label="")
        for m in memberships:
            label = m.label
            if label.startswith("Position"):
                label = f"{label} (citywide)"
            seats[m.person_id] = label
    return [
        {"name": name, "seat": seats.get(pk)}
        for pk, name in sorted(
            prefs.followed_reps.values_list("id", "name"),
            key=lambda pair: pair[1],
        )
    ]


def _item_context(item: dict) -> dict:
    return {
        # Stable id the Phase 5 blurb schema keys on.
        "item_id": f"{item['type']}-{item['id']}",
        "type": item["type"],
        "identifier": item["identifier"],
        "title": item["short_title"],
        "date": item["date"],
        "latest_action": item["latest_action"],
        "matched_because": item["reasons"],
        "summary": item["summary"],
    }


def digest_model() -> str:
    return settings.CLAUDE_DIGEST_MODEL
