# Generated by Django 4.2.30 on 2026-07-10 03:20

import digests.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    # NOTE: the councilmatic_core dep is pinned to 0053 — the last migration
    # that actually ships in the pinned django-councilmatic package. Running
    # `makemigrations` regenerates a phantom 0054 inside site-packages from
    # upstream model/migration drift (biography/headshot removals); depending
    # on it would break every environment that didn't locally generate it
    # (same failure mode as issue #187).
    dependencies = [
        ('councilmatic_core', '0053_add_councilmatic_bio'),
        ('core', '0009_auto_20241111_1450'),
        ('reps', '0004_repsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Stored lowercased so uniqueness is case-insensitive. Never log this value — use subscriber.id in code paths.', max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], db_index=True, default='pending', max_length=16)),
                ('verification_token', models.CharField(blank=True, default=None, help_text="One-shot double-opt-in token (secrets.token_urlsafe). Cleared on verification; NULL rows don't collide on the unique index.", max_length=64, null=True, unique=True)),
                ('unsubscribe_token_version', models.PositiveIntegerField(default=1, help_text="HMAC'd into manage/unsubscribe tokens. Bump to revoke all outstanding links for this subscriber.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='Start of the purge_unsubscribed retention clock.', null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_bounce_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Digest subscriber',
            },
        ),
        migrations.CreateModel(
            name='SubscriberPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_enabled', models.BooleanField(default=True)),
                ('daily_enabled', models.BooleanField(default=False, help_text="Daily-when-there's-news cadence. Accepted and stored from day one; the daily cron stays off until after launch.")),
                ('issue_areas', models.JSONField(blank=True, default=list, help_text='Subset of the BILL_TAG_VOCABULARY issue-area tags.', validators=[digests.models.validate_issue_areas])),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_subscribers', to='reps.district')),
                ('followed_bills', models.ManyToManyField(blank=True, help_text='Individual bills the subscriber follows.', related_name='digest_followers', to='councilmatic_core.bill')),
                ('followed_reps', models.ManyToManyField(blank=True, help_text='OCD Person rows for followed councilmembers.', related_name='digest_followers', to='core.person')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='digests.subscriber')),
            ],
            options={
                'verbose_name': 'Subscriber preferences',
                'verbose_name_plural': 'Subscriber preferences',
            },
        ),
        migrations.CreateModel(
            name='DigestSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], max_length=8)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('postmark_message_id', models.CharField(blank=True, default='', help_text='Provider message id. Empty under the SMTP transport.', max_length=100)),
                ('compose_batch_id', models.CharField(blank=True, default='', help_text="Anthropic Batch this send's LLM content came from. Empty for non-LLM sends (Phase 2 templated digests).", max_length=100)),
                ('bounce_status', models.CharField(blank=True, default='', help_text='Set by the Postmark webhook (Phase 4).', max_length=32)),
                ('matched_item_ids', models.JSONField(blank=True, default=list, help_text='Snapshot of [{type, id}, ...] items in this digest — not a live query. Read by the future feed page.')),
                ('llm_payload', models.JSONField(blank=True, help_text='Parsed LLM output for this send ({intro} in v1). Stored so re-render/debug never needs a second LLM call.', null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='digests.subscriber')),
            ],
            options={
                'verbose_name': 'Digest send',
                'indexes': [models.Index(fields=['subscriber', 'cadence', 'sent_at'], name='digests_dig_subscri_687ce5_idx')],
            },
        ),
    ]
