# Generated by Django 4.2.30 on 2026-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signups_enabled', models.BooleanField(help_text='Allow new digest signups. Off = subscribe endpoint 403s and the SPA hides the form; existing subscribers are unaffected.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Digest configuration',
                'verbose_name_plural': 'Digest configuration',
            },
        ),
    ]
