# Generated by Django 4.2.30 on 2026-07-10 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_digestconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestsend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When compose_digests created the row (composition time).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digestsend',
            name='error',
            field=models.CharField(blank=True, default='', help_text='Why a failed send failed. Email-redacted BEFORE storing — SMTP exceptions embed the recipient address and this field renders in the admin.', max_length=255),
        ),
        migrations.AddField(
            model_name='digestsend',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='digestsend',
            name='matched_item_ids',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of [{type, id, reasons}, ...] items in this digest — not a live query. Reasons are the compose-time match explanations; content (titles, summaries) is re-fetched by id at render time. Read by the future feed page.'),
        ),
        migrations.AlterField(
            model_name='digestsend',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Delivery time. NULL until send_digest_batches sends it.', null=True),
        ),
    ]
