# Generated by Django 4.2.25 on 2025-12-06 05:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="District number (1-7) or 'At Large'", max_length=10, unique=True)),
                ('name', models.CharField(help_text="e.g., 'District 1' or 'Citywide At Large'", max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='District boundary polygon(s)', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City Council District',
                'verbose_name_plural': 'City Council Districts',
                'ordering': ['number'],
            },
        ),
    ]
