# Generated by Django 4.2.30 on 2026-05-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241111_1450'),
        ('reps', '0003_repbio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text="2-3 paragraph plain-prose synthesis. Paragraphs joined with '\\n\\n'.")),
                ('stats_snapshot', models.JSONField(default=dict, help_text='Structured stats dict that was passed to the model — tenure, committees, sponsorship aggregates, voting record.')),
                ('model_version', models.CharField(blank=True, default='', help_text="Claude model that generated the summary (e.g. 'claude-sonnet-4-6-...').", max_length=100)),
                ('summary_batch_id', models.CharField(blank=True, default='', help_text='Anthropic Batch ID this summary came from. Empty for summaries generated outside a batch (e.g. ad-hoc retries).', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time the summary was (re-)generated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(help_text='OCD Person this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rep_summary', to='core.person')),
            ],
            options={
                'verbose_name': 'Rep LLM summary',
                'verbose_name_plural': 'Rep LLM summaries',
            },
        ),
    ]
