from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.db import models
from councilmatic_core.models import Bill, Event, Person, Organization
from datetime import datetime
import pytz

app_timezone = pytz.timezone(settings.TIME_ZONE)


class MunicipalCodeSection(models.Model):
    """
    A section of the Seattle Municipal Code (SMC).
    Parsed from the official PDF and stored for reference and summarization.
    """
    title_number = models.CharField(
        max_length=10,
        help_text="SMC title number (e.g., '23' for Land Use Code)"
    )
    chapter_number = models.CharField(
        max_length=20,
        blank=True,
        help_text="Chapter number (e.g., '23.45')"
    )
    section_number = models.CharField(
        max_length=30,
        db_index=True,
        help_text="Full section number (e.g., '23.45.010')"
    )
    title = models.CharField(
        max_length=500,
        help_text="Section title/heading"
    )
    full_text = models.TextField(
        help_text="Full text of this section"
    )
    plain_summary = models.TextField(
        blank=True,
        help_text="Plain-English summary generated by LLM"
    )
    summary_model = models.CharField(
        max_length=50,
        blank=True,
        help_text="Model used to generate summary (e.g., 'claude-3-haiku')"
    )
    summary_generated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the summary was generated"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="Page number in source PDF"
    )
    last_updated = models.DateTimeField(
        auto_now=True,
        help_text="When this section was last updated"
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['title_number', 'chapter_number', 'section_number']
        unique_together = ['title_number', 'chapter_number', 'section_number']
        verbose_name = "Municipal Code Section"
        verbose_name_plural = "Municipal Code Sections"

    def __str__(self):
        return f"SMC {self.section_number} - {self.title}"


class LegislationSummary(models.Model):
    """
    Plain-English summary and analysis of legislation (bills, ordinances, etc.).
    Links to affected municipal code sections.
    """
    bill = models.OneToOneField(
        Bill,
        on_delete=models.CASCADE,
        related_name='llm_summary',
        help_text="The legislation being summarized"
    )
    summary = models.TextField(
        help_text="Plain-English summary of what this legislation does"
    )
    impact_analysis = models.TextField(
        blank=True,
        help_text="Analysis of how this affects current municipal code"
    )
    affected_sections = models.ManyToManyField(
        MunicipalCodeSection,
        blank=True,
        related_name='affected_by_legislation',
        help_text="Municipal code sections this legislation modifies"
    )
    key_changes = models.JSONField(
        default=list,
        blank=True,
        help_text="Structured list of key changes"
    )
    model_version = models.CharField(
        max_length=50,
        help_text="Model used (e.g., 'claude-sonnet-4-20250514')"
    )
    generated_at = models.DateTimeField(
        auto_now_add=True
    )
    last_regenerated = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = "Legislation Summary"
        verbose_name_plural = "Legislation Summaries"

    def __str__(self):
        return f"Summary: {self.bill.identifier}"


class SeattleBill(Bill):
    """
    Extend the base Bill model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True

    def __str__(self):
        return self.friendly_name or self.identifier


class SeattleEvent(Event):
    """
    Extend the base Event model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True


class SeattlePerson(Person):
    """
    Extend the base Person model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True


class SeattleOrganization(Organization):
    """
    Extend the base Organization model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """

    class Meta:
        proxy = True


class ZoningPolygon(models.Model):
    """
    One polygon feature from Seattle SDCI's Land Use Zoning layer
    (Zoned_Development_Capacity_Layers_2016 FeatureServer layer 9).

    2,600+ polygons covering the entire city. `zoning` is the fully-
    qualified designation including modifiers (e.g., 'NC3-65'); `base_zone`
    is the FK to the base ZoningCode ('NC3') matching our legend table.
    Use this model as the spatial backbone: intersect with landmarks,
    council districts, or bill-referenced addresses.
    """
    object_id = models.IntegerField(
        unique=True,
        help_text="SDCI FeatureServer OBJECTID — identity key for upsert"
    )
    zone_id = models.IntegerField(
        db_index=True,
        help_text="SDCI ZONEID"
    )
    zoning = models.CharField(
        max_length=50,
        db_index=True,
        help_text="Full designation including modifiers (e.g., 'NC3-65')"
    )
    base_zone = models.ForeignKey(
        "ZoningCode",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="polygons",
        help_text="FK to the base zone legend entry; null if ZONELUT is not in our legend"
    )
    contract = models.CharField(max_length=40, blank=True)
    ordinance_number = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Ordinance that created/amended this zone"
    )
    effective_date = models.DateField(null=True, blank=True)
    historic = models.CharField(max_length=100, blank=True)
    pedestrian_overlay = models.CharField(max_length=100, blank=True)
    shoreline_overlay = models.CharField(max_length=100, blank=True)
    other_overlay = models.CharField(max_length=100, blank=True)
    lightrail_overlay = models.CharField(max_length=100, blank=True)
    previous_zone_id = models.IntegerField(null=True, blank=True)
    special_area_id = models.CharField(max_length=30, blank=True)
    boundary = gis_models.MultiPolygonField(srid=4326)
    source_url = models.URLField(max_length=500, blank=True)
    ingested_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["zoning", "object_id"]
        verbose_name = "Zoning Polygon"
        verbose_name_plural = "Zoning Polygons"

    def __str__(self):
        return f"{self.zoning} (#{self.object_id})"


class ZoningCode(models.Model):
    """
    One row of the Seattle zoning-district legend (e.g., 'NR1' → 'Residential,
    Neighborhood 1'). Parsed from the KEY TO DISTRICT DESIGNATIONS page of
    the SMC PDF.
    """
    abbreviation = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text="Zone code shown on maps (e.g., 'NR1')"
    )
    name = models.CharField(
        max_length=200,
        help_text="Full district name (e.g., 'Residential, Neighborhood 1')"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["abbreviation"]
        verbose_name = "Zoning Code"
        verbose_name_plural = "Zoning Codes"

    def __str__(self):
        return f"{self.abbreviation} — {self.name}"


class HistoricLandmark(models.Model):
    """
    A designated Seattle historic landmark. Ingested from SDCI's Landmarks
    FeatureServer (data-seattlecitygis.opendata.arcgis.com) — a point layer
    of ~500 landmarks with coordinates, ordinance numbers, designation
    documents, and photos.

    designation_type / designation_type_name capture the Roman-numeral
    grouping from SMC Ch. 25.32's PDF tables (I Residences, II Buildings,
    etc.) — nullable because the GIS source doesn't expose the grouping.
    Backfill from the PDF if a concrete use case emerges.
    """
    landmark_number = models.IntegerField(
        unique=True,
        null=True,
        blank=True,
        db_index=True,
        help_text="SDCI's stable landmark sequence ID (LANDNO); upsert key. "
                  "Nullable in the DB because Postgres permits multiple NULLs "
                  "under a unique index; the ingestion command enforces presence."
    )
    designation_type = models.CharField(
        max_length=10,
        blank=True,
        db_index=True,
        help_text="Roman numeral category code (I–IX); blank if unknown"
    )
    designation_type_name = models.CharField(
        max_length=60,
        blank=True,
        help_text="Human label for the category, e.g., 'Residences'"
    )
    name = models.CharField(
        max_length=300,
        db_index=True
    )
    address = models.CharField(
        max_length=500,
        blank=True
    )
    original_address = models.CharField(
        max_length=500,
        blank=True,
        help_text="Original address, if the landmark has since been renamed/readdressed"
    )
    designating_ord_number = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Ordinance that designated this landmark"
    )
    designation_date = models.DateField(
        null=True,
        blank=True,
        help_text="Effective date of designation (EFF_DATE in SDCI)"
    )
    photo_filename = models.CharField(
        max_length=300,
        blank=True,
        help_text="Filename of the landmark photo on Seattle.gov"
    )
    document_filename = models.CharField(
        max_length=300,
        blank=True,
        help_text="Filename of the designation report PDF on Seattle.gov"
    )
    geolocation = gis_models.PointField(
        srid=4326,
        null=True,
        blank=True,
        help_text="Point from SDCI's GIS layer (WGS84)"
    )
    council_district = models.ForeignKey(
        "reps.District",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="historic_landmarks",
        help_text="District resolved by point-in-polygon against geolocation"
    )
    source_url = models.URLField(
        max_length=500,
        blank=True
    )
    scraped_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["designation_type", "name"]
        verbose_name = "Historic Landmark"
        verbose_name_plural = "Historic Landmarks"

    def __str__(self):
        return f"{self.name} ({self.designation_type_name})"


class OrdinanceCodification(models.Model):
    """
    A row from the SMC's Table of Ordinances Codified (pp. 4397+ in the
    PDF), mapping one ordinance number to a human-readable description
    of what it did, plus the SMC chapter/section refs extracted from
    that description.
    """
    ordinance_number = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text="May be 'I-137' (initiative) or similar, not just numeric"
    )
    description = models.TextField(
        blank=True,
        help_text="Raw description text from the TOC row (e.g., "
                  "'Amends §§ 23.45.010, 23.45.020; adds § 23.45.025')"
    )
    adopted_date = models.DateField(
        null=True,
        blank=True,
        help_text="Adoption date if sourced from elsewhere; the PDF TOC lists only ord numbers"
    )
    codified_sections = models.JSONField(
        default=list,
        help_text="Chapter/section refs extracted from the description, e.g., "
                  "['23.45.010', '23.45.020', '25.32']"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where this row was extracted"
    )
    source_url = models.URLField(
        max_length=500,
        blank=True
    )
    scraped_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["-adopted_date", "ordinance_number"]
        verbose_name = "Ordinance Codification"
        verbose_name_plural = "Ordinance Codifications"

    def __str__(self):
        return f"Ord. {self.ordinance_number}"


class HistoricReviewDistrict(models.Model):
    """
    A Seattle historic or special-review overlay district. Eight of these
    cover specific neighborhoods (Pioneer Square, International District,
    Ballard Avenue, etc.) and impose additional design-review requirements
    on construction and alteration. Ingested from SDCI's 'Historic and
    Special Review Districts' polygon layer.
    """
    object_id = models.IntegerField(
        unique=True,
        db_index=True,
        help_text="SDCI FeatureServer OBJECTID — upsert key"
    )
    overlay_code = models.CharField(
        max_length=10,
        unique=True,
        db_index=True,
        help_text="Short code (e.g., 'ID', 'BD', 'PS')"
    )
    name = models.CharField(
        max_length=200,
        help_text="Full district name (e.g., 'Ballard Avenue Landmark District')"
    )
    purpose = models.TextField(
        blank=True,
        help_text="Purpose/preamble text from SDCI's public description"
    )
    district_type = models.CharField(
        max_length=20,
        db_index=True,
        help_text="'HISTORIC' for landmark districts, 'OVERLAY' for special review"
    )
    smc_chapter = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="SMC chapter that governs this district (e.g., '25.16'), "
                  "the 'Chapter ' prefix stripped for queryability"
    )
    chapter_link = models.URLField(
        max_length=500,
        blank=True,
        help_text="Municode URL to the governing SMC chapter"
    )
    boundary = gis_models.MultiPolygonField(srid=4326)
    source_url = models.URLField(max_length=500, blank=True)
    ingested_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["district_type", "name"]
        verbose_name = "Historic/Review District"
        verbose_name_plural = "Historic/Review Districts"

    def __str__(self):
        return self.name


class SectionOrdinanceRef(models.Model):
    """
    One revision parenthetical from a section's full_text. A section may
    have many (one per amending ordinance). Populated during PDF parsing,
    not by a separate scraper — the source is already in MunicipalCodeSection.
    """
    section = models.ForeignKey(
        MunicipalCodeSection,
        on_delete=models.CASCADE,
        related_name="ordinance_refs"
    )
    ordinance_number = models.CharField(
        max_length=20,
        db_index=True
    )
    ordinance_year = models.IntegerField(
        null=True,
        blank=True
    )
    section_reference = models.CharField(
        max_length=20,
        blank=True,
        help_text="Subsection within the ordinance, e.g., '§ 1'"
    )

    class Meta:
        ordering = ["section", "ordinance_year", "ordinance_number"]
        unique_together = ["section", "ordinance_number", "section_reference"]
        verbose_name = "Section Ordinance Reference"
        verbose_name_plural = "Section Ordinance References"

    def __str__(self):
        return f"{self.section.section_number} ← Ord. {self.ordinance_number}"

