from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import models
from councilmatic_core.models import Bill, Event, Person, Organization
from datetime import datetime
import pytz

app_timezone = pytz.timezone(settings.TIME_ZONE)


class MunicipalCodeSection(models.Model):
    """
    A section of the Seattle Municipal Code (SMC).
    Parsed from the official PDF and stored for reference and summarization.
    """
    title_number = models.CharField(
        max_length=10,
        help_text="SMC title number (e.g., '23' for Land Use Code)"
    )
    chapter_number = models.CharField(
        max_length=20,
        blank=True,
        help_text="Chapter number (e.g., '23.45')"
    )
    subchapter = models.ForeignKey(
        "Subchapter",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="sections",
        help_text="Subchapter grouping within the chapter, if any. "
                  "Populated during PDF parse when a 'Subchapter <Roman>' "
                  "divider is encountered."
    )
    section_number = models.CharField(
        max_length=30,
        db_index=True,
        help_text="Full section number (e.g., '23.45.010')"
    )
    title = models.CharField(
        max_length=500,
        help_text="Section title/heading"
    )
    full_text = models.TextField(
        help_text="Full text of this section"
    )
    plain_summary = models.TextField(
        blank=True,
        help_text="Plain-English summary generated by LLM"
    )
    summary_model = models.CharField(
        max_length=50,
        blank=True,
        help_text="Model used to generate summary (e.g., 'claude-3-haiku')"
    )
    summary_generated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the summary was generated"
    )
    summary_batch_id = models.CharField(
        max_length=64,
        blank=True,
        help_text=(
            "Anthropic Message Batches ID this summary came from "
            "(e.g., 'msgbatch_01PCxUY7AHperTdVueAxmYr7'). Empty for "
            "synchronous one-off generations or legacy rows."
        ),
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="Page number in source PDF"
    )
    last_updated = models.DateTimeField(
        auto_now=True,
        help_text="When this section was last updated"
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    # PG-generated tsvector. Column is GENERATED ALWAYS AS ... STORED at the
    # DB level (see migration 0014); Django never writes to it.
    search_vector = SearchVectorField(null=True, editable=False)

    class Meta:
        ordering = ['title_number', 'chapter_number', 'section_number']
        unique_together = ['title_number', 'chapter_number', 'section_number']
        indexes = [
            GinIndex(fields=['search_vector'], name='smc_section_search_idx'),
            GinIndex(
                fields=['section_number'],
                name='smc_section_number_trgm_idx',
                opclasses=['gin_trgm_ops'],
            ),
        ]
        verbose_name = "Municipal Code Section"
        verbose_name_plural = "Municipal Code Sections"

    def __str__(self):
        return f"SMC {self.section_number} - {self.title}"


class TitleAppendix(models.Model):
    """
    An appendix attached to an SMC Title — currently only Title 15's
    parks/scenic-routes appendix (pages 2047–2086, referenced by SEPA
    and zoning code). Appendices are standalone from MunicipalCodeSection
    because they have no section number and follow a different structure
    (lists of named items like park drives, view rights-of-way), not
    numbered paragraphs.
    """
    title_number = models.CharField(
        max_length=10,
        db_index=True,
        help_text="SMC title number this appendix attaches to (e.g., '15')"
    )
    label = models.CharField(
        max_length=20,
        help_text="Roman-numeral label as it appears in the heading "
                  "(e.g., 'I', 'I AND II')"
    )
    full_text = models.TextField(
        help_text="Body text of the appendix"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="Page number where the appendix heading appears in the source PDF"
    )
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title_number', 'label']
        unique_together = ['title_number', 'label']
        verbose_name = "Title Appendix"
        verbose_name_plural = "Title Appendices"

    def __str__(self):
        return f"Title {self.title_number} Appendix {self.label}"


class CodeTitle(models.Model):
    """
    Human-readable name of an SMC title (e.g., '23' -> 'LAND USE CODE').
    Populated by the extract_smc_toc management command from the
    Detailed Table of Contents in the SMC PDF (pages 149-168 of the
    20260421 snapshot). Names are stored as printed in the TOC, mostly
    in upper case.
    """
    title_number = models.CharField(
        max_length=10,
        unique=True,
        help_text="SMC title number, e.g. '23' or '12A'"
    )
    name = models.CharField(
        max_length=200,
        help_text="Title name as printed in the TOC, e.g. 'LAND USE CODE'"
    )
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title_number']
        verbose_name = "Code Title"
        verbose_name_plural = "Code Titles"

    def __str__(self):
        return f"Title {self.title_number} - {self.name}"


class CodeChapter(models.Model):
    """
    Human-readable name of an SMC chapter (e.g., '23.47A' -> 'Commercial').
    Populated by the extract_smc_toc command alongside CodeTitle. Names
    in the TOC are mixed case ('Code Adoption', 'Election Campaign
    Contributions') and may include em-dashes ('Citation—Hearings—
    Penalties') or wrap onto multiple lines in the source PDF (folded
    by the extractor).
    """
    chapter_number = models.CharField(
        max_length=20,
        unique=True,
        help_text="Chapter number, e.g. '23.47A'"
    )
    title_number = models.CharField(
        max_length=10,
        db_index=True,
        help_text="Parent title number, e.g. '23'"
    )
    name = models.CharField(
        max_length=300,
        help_text="Chapter name as printed in the TOC"
    )
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['chapter_number']
        verbose_name = "Code Chapter"
        verbose_name_plural = "Code Chapters"

    def __str__(self):
        return f"Chapter {self.chapter_number} - {self.name}"


class LegislationSummary(models.Model):
    """
    Plain-English summary and analysis of legislation (bills, ordinances, etc.).
    Links to affected municipal code sections.
    """
    bill = models.OneToOneField(
        Bill,
        on_delete=models.CASCADE,
        related_name='llm_summary',
        help_text="The legislation being summarized"
    )
    summary = models.TextField(
        help_text="Plain-English summary of what this legislation does"
    )
    impact_analysis = models.TextField(
        blank=True,
        help_text="Analysis of how this affects current municipal code"
    )
    affected_sections = models.ManyToManyField(
        MunicipalCodeSection,
        blank=True,
        related_name='affected_by_legislation',
        help_text="Municipal code sections this legislation modifies"
    )
    key_changes = models.JSONField(
        default=list,
        blank=True,
        help_text="Structured list of key changes"
    )
    model_version = models.CharField(
        max_length=50,
        help_text="Model used (e.g., 'claude-sonnet-4-20250514')"
    )
    generated_at = models.DateTimeField(
        auto_now_add=True
    )
    last_regenerated = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = "Legislation Summary"
        verbose_name_plural = "Legislation Summaries"

    def __str__(self):
        return f"Summary: {self.bill.identifier}"


class SeattleBill(Bill):
    """
    Extend the base Bill model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True

    def __str__(self):
        return self.friendly_name or self.identifier


class SeattleEvent(Event):
    """
    Extend the base Event model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True


class SeattlePerson(Person):
    """
    Extend the base Person model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True


class SeattleOrganization(Organization):
    """
    Extend the base Organization model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """

    class Meta:
        proxy = True


class ZoningPolygon(models.Model):
    """
    One polygon feature from Seattle SDCI's Land Use Zoning layer
    (Zoned_Development_Capacity_Layers_2016 FeatureServer layer 9).

    2,600+ polygons covering the entire city. `zoning` is the fully-
    qualified designation including modifiers (e.g., 'NC3-65'); `base_zone`
    is the FK to the base ZoningCode ('NC3') matching our legend table.
    Use this model as the spatial backbone: intersect with landmarks,
    council districts, or bill-referenced addresses.
    """
    object_id = models.IntegerField(
        unique=True,
        help_text="SDCI FeatureServer OBJECTID — identity key for upsert"
    )
    zone_id = models.IntegerField(
        db_index=True,
        help_text="SDCI ZONEID"
    )
    zoning = models.CharField(
        max_length=50,
        db_index=True,
        help_text="Full designation including modifiers (e.g., 'NC3-65')"
    )
    base_zone = models.ForeignKey(
        "ZoningCode",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="polygons",
        help_text="FK to the base zone legend entry; null if ZONELUT is not in our legend"
    )
    contract = models.CharField(max_length=40, blank=True)
    ordinance_number = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Ordinance that created/amended this zone"
    )
    effective_date = models.DateField(null=True, blank=True)
    historic = models.CharField(max_length=100, blank=True)
    pedestrian_overlay = models.CharField(max_length=100, blank=True)
    shoreline_overlay = models.CharField(max_length=100, blank=True)
    other_overlay = models.CharField(max_length=100, blank=True)
    lightrail_overlay = models.CharField(max_length=100, blank=True)
    previous_zone_id = models.IntegerField(null=True, blank=True)
    special_area_id = models.CharField(max_length=30, blank=True)
    boundary = gis_models.MultiPolygonField(srid=4326)
    source_url = models.URLField(max_length=500, blank=True)
    ingested_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["zoning", "object_id"]
        verbose_name = "Zoning Polygon"
        verbose_name_plural = "Zoning Polygons"

    def __str__(self):
        return f"{self.zoning} (#{self.object_id})"


class ZoningCode(models.Model):
    """
    One row of the Seattle zoning-district legend (e.g., 'NR1' → 'Residential,
    Neighborhood 1'). Parsed from the KEY TO DISTRICT DESIGNATIONS page of
    the SMC PDF.
    """
    abbreviation = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text="Zone code shown on maps (e.g., 'NR1')"
    )
    name = models.CharField(
        max_length=200,
        help_text="Full district name (e.g., 'Residential, Neighborhood 1')"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["abbreviation"]
        verbose_name = "Zoning Code"
        verbose_name_plural = "Zoning Codes"

    def __str__(self):
        return f"{self.abbreviation} — {self.name}"


class HistoricLandmark(models.Model):
    """
    A designated Seattle historic landmark. Ingested from SDCI's Landmarks
    FeatureServer (data-seattlecitygis.opendata.arcgis.com) — a point layer
    of ~500 landmarks with coordinates, ordinance numbers, designation
    documents, and photos.

    designation_type / designation_type_name capture the Roman-numeral
    grouping from SMC Ch. 25.32's PDF tables (I Residences, II Buildings,
    etc.) — nullable because the GIS source doesn't expose the grouping.
    Backfill from the PDF if a concrete use case emerges.
    """
    landmark_number = models.IntegerField(
        unique=True,
        null=True,
        blank=True,
        db_index=True,
        help_text="SDCI's stable landmark sequence ID (LANDNO); upsert key. "
                  "Nullable in the DB because Postgres permits multiple NULLs "
                  "under a unique index; the ingestion command enforces presence."
    )
    designation_type = models.CharField(
        max_length=10,
        blank=True,
        db_index=True,
        help_text="Roman numeral category code (I–IX); blank if unknown"
    )
    designation_type_name = models.CharField(
        max_length=60,
        blank=True,
        help_text="Human label for the category, e.g., 'Residences'"
    )
    name = models.CharField(
        max_length=300,
        db_index=True
    )
    address = models.CharField(
        max_length=500,
        blank=True
    )
    original_address = models.CharField(
        max_length=500,
        blank=True,
        help_text="Original address, if the landmark has since been renamed/readdressed"
    )
    designating_ord_number = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Ordinance that designated this landmark"
    )
    designation_date = models.DateField(
        null=True,
        blank=True,
        help_text="Effective date of designation (EFF_DATE in SDCI)"
    )
    photo_filename = models.CharField(
        max_length=300,
        blank=True,
        help_text="Filename of the landmark photo on Seattle.gov"
    )
    document_filename = models.CharField(
        max_length=300,
        blank=True,
        help_text="Filename of the designation report PDF on Seattle.gov"
    )
    geolocation = gis_models.PointField(
        srid=4326,
        null=True,
        blank=True,
        help_text="Point from SDCI's GIS layer (WGS84)"
    )
    council_district = models.ForeignKey(
        "reps.District",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="historic_landmarks",
        help_text="District resolved by point-in-polygon against geolocation"
    )
    source_url = models.URLField(
        max_length=500,
        blank=True
    )
    scraped_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["designation_type", "name"]
        verbose_name = "Historic Landmark"
        verbose_name_plural = "Historic Landmarks"

    def __str__(self):
        return f"{self.name} ({self.designation_type_name})"


class OrdinanceCodification(models.Model):
    """
    A row from the SMC's Table of Ordinances Codified (pp. 4397+ in the
    PDF), mapping one ordinance number to a human-readable description
    of what it did, plus the SMC chapter/section refs extracted from
    that description.
    """
    ordinance_number = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text="May be 'I-137' (initiative) or similar, not just numeric"
    )
    description = models.TextField(
        blank=True,
        help_text="Raw description text from the TOC row (e.g., "
                  "'Amends §§ 23.45.010, 23.45.020; adds § 23.45.025')"
    )
    adopted_date = models.DateField(
        null=True,
        blank=True,
        help_text="Adoption date if sourced from elsewhere; the PDF TOC lists only ord numbers"
    )
    codified_sections = models.JSONField(
        default=list,
        help_text="Chapter/section refs extracted from the description, e.g., "
                  "['23.45.010', '23.45.020', '25.32']"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where this row was extracted"
    )
    source_url = models.URLField(
        max_length=500,
        blank=True
    )
    scraped_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["-adopted_date", "ordinance_number"]
        verbose_name = "Ordinance Codification"
        verbose_name_plural = "Ordinance Codifications"

    def __str__(self):
        return f"Ord. {self.ordinance_number}"


class HistoricReviewDistrict(models.Model):
    """
    A Seattle historic or special-review overlay district. Eight of these
    cover specific neighborhoods (Pioneer Square, International District,
    Ballard Avenue, etc.) and impose additional design-review requirements
    on construction and alteration. Ingested from SDCI's 'Historic and
    Special Review Districts' polygon layer.
    """
    object_id = models.IntegerField(
        unique=True,
        db_index=True,
        help_text="SDCI FeatureServer OBJECTID — upsert key"
    )
    overlay_code = models.CharField(
        max_length=10,
        unique=True,
        db_index=True,
        help_text="Short code (e.g., 'ID', 'BD', 'PS')"
    )
    name = models.CharField(
        max_length=200,
        help_text="Full district name (e.g., 'Ballard Avenue Landmark District')"
    )
    purpose = models.TextField(
        blank=True,
        help_text="Purpose/preamble text from SDCI's public description"
    )
    district_type = models.CharField(
        max_length=20,
        db_index=True,
        help_text="'HISTORIC' for landmark districts, 'OVERLAY' for special review"
    )
    smc_chapter = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="SMC chapter that governs this district (e.g., '25.16'), "
                  "the 'Chapter ' prefix stripped for queryability"
    )
    chapter_link = models.URLField(
        max_length=500,
        blank=True,
        help_text="Municode URL to the governing SMC chapter"
    )
    boundary = gis_models.MultiPolygonField(srid=4326)
    source_url = models.URLField(max_length=500, blank=True)
    ingested_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["district_type", "name"]
        verbose_name = "Historic/Review District"
        verbose_name_plural = "Historic/Review Districts"

    def __str__(self):
        return self.name


class SectionOrdinanceRef(models.Model):
    """
    One revision parenthetical from a section's full_text. A section may
    have many (one per amending ordinance). Populated during PDF parsing,
    not by a separate scraper — the source is already in MunicipalCodeSection.
    """
    section = models.ForeignKey(
        MunicipalCodeSection,
        on_delete=models.CASCADE,
        related_name="ordinance_refs"
    )
    ordinance_number = models.CharField(
        max_length=20,
        db_index=True
    )
    ordinance_year = models.IntegerField(
        null=True,
        blank=True
    )
    section_reference = models.CharField(
        max_length=20,
        blank=True,
        help_text="Subsection within the ordinance, e.g., '§ 1'"
    )

    class Meta:
        ordering = ["section", "ordinance_year", "ordinance_number"]
        unique_together = ["section", "ordinance_number", "section_reference"]
        verbose_name = "Section Ordinance Reference"
        verbose_name_plural = "Section Ordinance References"

    def __str__(self):
        return f"{self.section.section_number} ← Ord. {self.ordinance_number}"


class Subchapter(models.Model):
    """
    A subchapter within an SMC chapter (e.g., Ch. 25.05 Subchapter IX
    "Categorical Exemptions"). Populated by parse_smc_pdf from two sources:

      - Official: scraped from the chapter's table of contents at the
        start of the chapter in the PDF. Authoritative section list.
      - Synthesized: reconstructed from body-divider lines
        ("Subchapter <Roman> <Name>") when no TOC was found for the
        chapter. Section list inferred from parse emissions.

    declared_section_numbers is the TOC-asserted section list for this
    subchapter. Comparing it to sections.values_list('section_number') at
    validation time surfaces parse regressions (either a section the TOC
    claims but the body parse missed, or a section parsed but not listed
    in the TOC). Mismatches are recorded as ParseValidationIssue rows.
    """
    SOURCE_OFFICIAL = "official"
    SOURCE_SYNTHESIZED = "synthesized"
    SOURCE_CHOICES = [
        (SOURCE_OFFICIAL, "Official (from PDF TOC)"),
        (SOURCE_SYNTHESIZED, "Synthesized (from body parse)"),
    ]

    chapter_number = models.CharField(
        max_length=20,
        db_index=True,
        help_text="Parent chapter number, e.g., '25.05'"
    )
    roman = models.CharField(
        max_length=10,
        help_text="Roman numeral as printed, e.g., 'IX'"
    )
    ordinal = models.PositiveSmallIntegerField(
        help_text="Integer equivalent of roman (IX -> 9). Used for ORDER BY."
    )
    name = models.CharField(
        max_length=200,
        blank=True,
        help_text="Subchapter name, e.g., 'Categorical Exemptions'. "
                  "Blank when the divider is bare 'Subchapter <Roman>'."
    )
    toc_source = models.CharField(
        max_length=20,
        choices=SOURCE_CHOICES,
        help_text="Whether declared_section_numbers came from an official "
                  "PDF TOC or was synthesized from body parse emissions."
    )
    toc_source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where the TOC entry for this subchapter was parsed."
    )
    body_source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where the in-body 'Subchapter <Roman> <Name>' "
                  "divider appears."
    )
    declared_section_numbers = models.JSONField(
        default=list,
        help_text="Section numbers declared under this subchapter in the "
                  "TOC, in document order, e.g., ['25.05.800', '25.05.810']."
    )

    class Meta:
        ordering = ["chapter_number", "ordinal"]
        unique_together = ["chapter_number", "roman"]
        verbose_name = "Subchapter"
        verbose_name_plural = "Subchapters"

    def __str__(self):
        label = f"{self.chapter_number} Subchapter {self.roman}"
        return f"{label}: {self.name}" if self.name else label


class ParseValidationIssue(models.Model):
    """
    A parse-time discrepancy between what a TOC declares and what the body
    pass actually emitted. Written by parse_smc_pdf's validation step and
    overwritten on every run (old rows deleted, new ones recorded).

    The parser never fails on a mismatch — these rows are the audit trail
    so regressions are visible without blocking ingest.
    """
    CAT_MISSING_FROM_BODY = "missing_from_body"
    CAT_UNDECLARED_IN_TOC = "undeclared_in_toc"
    CATEGORY_CHOICES = [
        (CAT_MISSING_FROM_BODY, "Declared in TOC but not emitted by body parse"),
        (CAT_UNDECLARED_IN_TOC, "Emitted by body parse but not declared in TOC"),
    ]

    subchapter = models.ForeignKey(
        Subchapter,
        on_delete=models.CASCADE,
        related_name="validation_issues"
    )
    category = models.CharField(
        max_length=32,
        choices=CATEGORY_CHOICES,
        db_index=True
    )
    section_number = models.CharField(
        max_length=32,
        blank=True,
        help_text="The section this issue concerns, if any."
    )
    message = models.TextField(
        blank=True,
        help_text="Free-form description of the issue."
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["subchapter", "category", "section_number"]
        verbose_name = "Parse Validation Issue"
        verbose_name_plural = "Parse Validation Issues"

    def __str__(self):
        return f"[{self.category}] {self.subchapter} — {self.section_number}"
