from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import models
from councilmatic_core.models import Bill, Event, Person, Organization
from datetime import datetime
import pytz

app_timezone = pytz.timezone(settings.TIME_ZONE)


class _GeneratedColumnAwareManager(models.Manager):
    """Drops generated-column field names from the INSERT field list.

    Migration 0014 made `MunicipalCodeSection.search_vector` a
    `GENERATED ALWAYS AS ... STORED` tsvector at the DB level — its
    value is computed from `section_number`, `title`, and `full_text`
    by Postgres. Django's model state knows nothing about that
    generation, so the default INSERT path includes a NULL value
    for `search_vector` and Postgres rejects with:

        cannot insert a non-DEFAULT value into column "search_vector"

    This bites every code path that creates a row from scratch:
    `Model.objects.create()`, `instance.save()` on a new object,
    `bulk_create()`. Existing rows go through the UPDATE path which
    happens to omit the field, which is why the bug was latent for
    months — UPDATE-only re-parses didn't surface it; the first
    INSERT in `parse_smc_pdf` did.

    Fix: subclass the default manager and strip configured field
    names from the INSERT field list before delegating. Affects
    INSERTs only — UPDATEs are routed through `_update`, untouched.
    Subclasses set `excluded_from_insert` to a tuple of field names.
    """

    excluded_from_insert: tuple[str, ...] = ()

    def _insert(self, objs, fields, *args, **kwargs):
        if self.excluded_from_insert:
            fields = [f for f in fields if f.name not in self.excluded_from_insert]
        return super()._insert(objs, fields, *args, **kwargs)


class _MunicipalCodeSectionManager(_GeneratedColumnAwareManager):
    excluded_from_insert = ("search_vector",)


class MunicipalCodeSection(models.Model):
    """
    A section of the Seattle Municipal Code (SMC).
    Parsed from the official PDF and stored for reference and summarization.
    """
    title_number = models.CharField(
        max_length=10,
        help_text="SMC title number (e.g., '23' for Land Use Code)"
    )
    chapter_number = models.CharField(
        max_length=20,
        blank=True,
        help_text="Chapter number (e.g., '23.45')"
    )
    subchapter = models.ForeignKey(
        "Subchapter",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="sections",
        help_text="Subchapter grouping within the chapter, if any. "
                  "Populated during PDF parse when a 'Subchapter <Roman>' "
                  "divider is encountered."
    )
    section_number = models.CharField(
        max_length=30,
        db_index=True,
        help_text="Full section number (e.g., '23.45.010')"
    )
    title = models.CharField(
        max_length=500,
        help_text="Section title/heading"
    )
    full_text = models.TextField(
        help_text="Full text of this section"
    )
    plain_summary = models.TextField(
        blank=True,
        help_text="Plain-English summary generated by LLM"
    )
    summary_model = models.CharField(
        max_length=50,
        blank=True,
        help_text="Model used to generate summary (e.g., 'claude-3-haiku')"
    )
    summary_generated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the summary was generated"
    )
    summary_batch_id = models.CharField(
        max_length=64,
        blank=True,
        help_text=(
            "Anthropic Message Batches ID this summary came from "
            "(e.g., 'msgbatch_01PCxUY7AHperTdVueAxmYr7'). Empty for "
            "synchronous one-off generations or legacy rows."
        ),
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="Page number in source PDF"
    )
    last_updated = models.DateTimeField(
        auto_now=True,
        help_text="When this section was last updated"
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    # PG-generated tsvector. Column is GENERATED ALWAYS AS ... STORED at the
    # DB level (see migration 0014); Django never writes to it. Custom
    # manager below strips it from INSERT field lists so Django's
    # default ORM path doesn't try to send NULL for it.
    search_vector = SearchVectorField(null=True, editable=False)

    objects = _MunicipalCodeSectionManager()

    class Meta:
        # `base_manager_name = "objects"` is the magic that makes
        # Django route INSERTs through our custom manager. Without
        # this, `Model._base_manager` falls back to a vanilla
        # `Manager()` instance, the manager's `_insert` override is
        # never called, and the search_vector exclusion silently
        # does nothing. (Django 4.2 docs note this; the default-
        # manager-as-base behavior some references describe is only
        # for older versions.)
        base_manager_name = "objects"
        ordering = ['title_number', 'chapter_number', 'section_number']
        unique_together = ['title_number', 'chapter_number', 'section_number']
        indexes = [
            GinIndex(fields=['search_vector'], name='smc_section_search_idx'),
            GinIndex(
                fields=['section_number'],
                name='smc_section_number_trgm_idx',
                opclasses=['gin_trgm_ops'],
            ),
        ]
        verbose_name = "Municipal Code Section"
        verbose_name_plural = "Municipal Code Sections"

    def __str__(self):
        return f"SMC {self.section_number} - {self.title}"


class TitleAppendix(models.Model):
    """
    An appendix attached to an SMC Title — currently only Title 15's
    parks/scenic-routes appendix (pages 2047–2086, referenced by SEPA
    and zoning code). Appendices are standalone from MunicipalCodeSection
    because they have no section number and follow a different structure
    (lists of named items like park drives, view rights-of-way), not
    numbered paragraphs.
    """
    title_number = models.CharField(
        max_length=10,
        db_index=True,
        help_text="SMC title number this appendix attaches to (e.g., '15')"
    )
    label = models.CharField(
        max_length=20,
        help_text="Roman-numeral label as it appears in the heading "
                  "(e.g., 'I', 'I AND II')"
    )
    full_text = models.TextField(
        help_text="Body text of the appendix"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="Page number where the appendix heading appears in the source PDF"
    )
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title_number', 'label']
        unique_together = ['title_number', 'label']
        verbose_name = "Title Appendix"
        verbose_name_plural = "Title Appendices"

    def __str__(self):
        return f"Title {self.title_number} Appendix {self.label}"


class CodeTitle(models.Model):
    """
    Human-readable name of an SMC title (e.g., '23' -> 'LAND USE CODE').
    Populated by the extract_smc_toc management command from the
    Detailed Table of Contents in the SMC PDF (pages 149-168 of the
    20260421 snapshot). Names are stored as printed in the TOC, mostly
    in upper case.
    """
    title_number = models.CharField(
        max_length=10,
        unique=True,
        help_text="SMC title number, e.g. '23' or '12A'"
    )
    name = models.CharField(
        max_length=200,
        help_text="Title name as printed in the TOC, e.g. 'LAND USE CODE'"
    )
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['title_number']
        verbose_name = "Code Title"
        verbose_name_plural = "Code Titles"

    def __str__(self):
        return f"Title {self.title_number} - {self.name}"


class CodeChapter(models.Model):
    """
    Human-readable name of an SMC chapter (e.g., '23.47A' -> 'Commercial').
    Populated by the extract_smc_toc command alongside CodeTitle. Names
    in the TOC are mixed case ('Code Adoption', 'Election Campaign
    Contributions') and may include em-dashes ('Citation—Hearings—
    Penalties') or wrap onto multiple lines in the source PDF (folded
    by the extractor).
    """
    chapter_number = models.CharField(
        max_length=20,
        unique=True,
        help_text="Chapter number, e.g. '23.47A'"
    )
    title_number = models.CharField(
        max_length=10,
        db_index=True,
        help_text="Parent title number, e.g. '23'"
    )
    name = models.CharField(
        max_length=300,
        help_text="Chapter name as printed in the TOC"
    )
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['chapter_number']
        verbose_name = "Code Chapter"
        verbose_name_plural = "Code Chapters"

    def __str__(self):
        return f"Chapter {self.chapter_number} - {self.name}"


class LegislationSummary(models.Model):
    """
    Plain-English summary and analysis of legislation (bills, ordinances, etc.).
    Links to affected municipal code sections.
    """
    bill = models.OneToOneField(
        Bill,
        on_delete=models.CASCADE,
        related_name='llm_summary',
        help_text="The legislation being summarized"
    )
    summary = models.TextField(
        help_text="Plain-English summary of what this legislation does"
    )
    impact_analysis = models.TextField(
        blank=True,
        help_text="Analysis of how this affects current municipal code"
    )
    affected_sections = models.ManyToManyField(
        MunicipalCodeSection,
        blank=True,
        related_name='affected_by_legislation',
        help_text="Municipal code sections this legislation modifies"
    )
    key_changes = models.JSONField(
        default=list,
        blank=True,
        help_text="Structured list of key changes"
    )
    model_version = models.CharField(
        max_length=50,
        help_text="Model used (e.g., 'claude-sonnet-4-20250514')"
    )
    summary_batch_id = models.CharField(
        max_length=64,
        blank=True,
        help_text=(
            "Anthropic Message Batches ID this summary came from "
            "(e.g., 'msgbatch_01PCxUY7AHperTdVueAxmYr7'). Empty for "
            "synchronous one-off generations."
        ),
    )
    generated_at = models.DateTimeField(
        auto_now_add=True
    )
    last_regenerated = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name = "Legislation Summary"
        verbose_name_plural = "Legislation Summaries"

    def __str__(self):
        return f"Summary: {self.bill.identifier}"


class BillText(models.Model):
    """Extracted plain text of a Bill's substantive attachments.

    Seattle bills carry their content in Legistar document attachments
    — typically a "Summary and Fiscal Note" (.docx) plus, after
    enactment, a "Signed Ordinance NNNNN" (.pdf). The OCD/pupa Bill row
    only stores attachment URLs, so this model is the cache of their
    extracted plain text, keyed 1:1 by Bill. The bill summarizer
    reads from `text` instead of re-downloading on every LLM call.

    `source_documents` is the audit trail: which attachments were
    extracted, what category they fell into, what their byte sizes were,
    and any per-document error message. Re-running extraction overwrites
    `text` and refreshes the audit trail.
    """
    bill = models.OneToOneField(
        Bill,
        on_delete=models.CASCADE,
        related_name="extracted_text",
        help_text="The legislation whose attachments produced this text.",
    )
    text = models.TextField(
        blank=True,
        help_text=(
            "Concatenated plain text of all chosen attachments, with "
            "section markers between sources (staff summary first, then "
            "signed canonical text)."
        ),
    )
    source_documents = models.JSONField(
        default=list,
        blank=True,
        help_text=(
            "Per-document audit trail: list of "
            "{note, url, media_type, category, char_count, error}."
        ),
    )
    extracted_at = models.DateTimeField(auto_now_add=True)
    last_regenerated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Bill Text"
        verbose_name_plural = "Bill Texts"

    def __str__(self):
        return f"Text: {self.bill.identifier} ({len(self.text):,} chars)"


class EventTranscript(models.Model):
    """Captioned transcript of a council meeting, scraped from Seattle
    Channel's video archive. One row per ``Event`` (typically Full
    Council meetings; the extractor is filterable but defaults to that).

    Seattle Channel publishes auto-captioned SRT files at a
    deterministic URL once a meeting is archived. The SRT is the raw
    source of truth and stays preserved in ``srt_raw`` for future
    re-processing without re-scraping. ``transcript_text`` is the
    flattened plain-text view (entities decoded, timestamps + sequence
    numbers stripped) for cheap LLM consumption.

    ``chapter_markers`` mirrors the agenda-item index on the Seattle
    Channel video page: a list of ``{label, start_seconds}`` dicts
    ordered by time. The summarizer (issue #149 phase 2) uses these
    to chunk the transcript for per-agenda-item summaries.

    Caption quality is auto-captioned (all-caps, proper-noun errors,
    speaker turns marked only by ``>>`` not by name). Quality is
    mitigated at LLM-summary time by passing the meeting's agenda +
    councilmember roster as structured context. ``video_url`` is
    captured so a future Whisper re-transcription step (issue #149
    phase 3, deferred) wouldn't need to re-scrape Seattle Channel."""

    event = models.OneToOneField(
        Event,
        on_delete=models.CASCADE,
        related_name="transcript",
        help_text="The council meeting this transcript belongs to.",
    )
    srt_raw = models.TextField(
        help_text="Raw SRT as downloaded from Seattle Channel.",
    )
    transcript_text = models.TextField(
        help_text=(
            "Flattened plain text of the SRT (timestamps + sequence "
            "numbers stripped, HTML entities decoded). Speaker-turn "
            "markers '>>' preserved for chunkability."
        ),
    )
    chapter_markers = models.JSONField(
        default=list,
        help_text=(
            "Ordered list of {label, start_seconds} dicts from the "
            "Seattle Channel agenda-index UI. Empty when a meeting "
            "had no marked chapters."
        ),
    )
    source_url = models.URLField(
        max_length=500,
        help_text="Seattle Channel URL the SRT was downloaded from.",
    )
    video_url = models.URLField(
        max_length=500,
        blank=True,
        default="",
        help_text=(
            "video.seattle.gov MP4 URL for the meeting. Captured for "
            "future Whisper re-transcription; not used by the v1 "
            "SRT-based summarizer."
        ),
    )
    scraped_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Event Transcript"
        verbose_name_plural = "Event Transcripts"

    def __str__(self):
        n = len(self.transcript_text)
        return f"Transcript for {self.event} ({n:,} chars)"


class EventSummary(models.Model):
    """LLM-generated summary of a council meeting. One row per ``Event``,
    synthesized from the ``EventTranscript.transcript_text`` plus the
    meeting's agenda items and the current councilmember roster as
    structured prompt context (the roster lets the model cross-reference
    garbled auto-caption names against the real people who could plausibly
    have spoken).

    Two-tier shape:
      - ``overview`` is the 2-4 paragraph plain-prose meeting summary
        that the EventDetail card displays by default.
      - ``item_summaries`` is a list of ``{label, start_seconds, summary}``
        dicts, one per agenda-item chapter from the SRT chunker. The
        frontend renders these as collapsible sections under the overview.

    ``stats_snapshot`` records the structured context that was passed to
    the LLM (agenda items, roster, validated chapter list) so a future
    re-generation against the same inputs is reproducible without
    re-aggregating. Re-summarization is idempotent — ``summarize_events``
    UPSERTs by ``event_id``."""

    event = models.OneToOneField(
        Event,
        on_delete=models.CASCADE,
        related_name="llm_summary",
        help_text="The council meeting this summary belongs to.",
    )
    overview = models.TextField(
        help_text="2-4 paragraph plain-prose meeting overview.",
    )
    item_summaries = models.JSONField(
        default=list,
        help_text=(
            "Per-agenda-item summaries: list of "
            "{label, start_seconds, summary} dicts ordered by time."
        ),
    )
    stats_snapshot = models.JSONField(
        default=dict,
        help_text=(
            "Structured prompt context passed to the LLM — agenda items, "
            "councilmember roster, validated chapter list. Reproducibility "
            "audit trail."
        ),
    )
    model_version = models.CharField(
        max_length=100,
        blank=True,
        default="",
        help_text="Claude model that generated the summary.",
    )
    summary_batch_id = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text=(
            "Anthropic Message Batches ID this summary came from. "
            "Empty for synchronous one-off retries."
        ),
    )
    generated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last time the summary was (re-)generated.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Event LLM Summary"
        verbose_name_plural = "Event LLM Summaries"

    def __str__(self):
        return f"Summary for {self.event}"


class CommitteeProfile(models.Model):
    """Scope + regular meeting schedule scraped from a committee's seattle.gov
    page. One row per OCD ``Organization`` (committee). The committee page
    publishes an authoritative "Committee Scope:" block (the departments and
    policy areas the committee oversees) and a "Committee regular meeting days
    and time:" line — neither of which is in the OCD scrape, so we fetch them
    here and feed them into the committee LLM summary as ground truth (rather
    than letting the model infer the remit from bill titles alone).

    Mirrors ``RepBio``: raw scraped text, idempotent UPSERT by
    ``organization_id`` (``scrape_committee_info``), safe to schedule weekly —
    scope/schedule change rarely (committee reorganizations)."""

    organization = models.OneToOneField(
        "core.Organization",
        on_delete=models.CASCADE,
        related_name="committee_profile",
        help_text="OCD Organization (committee) this profile belongs to.",
    )
    scope = models.TextField(
        blank=True,
        default="",
        help_text="The committee's scope/remit prose from its seattle.gov "
        "'Committee Scope:' section.",
    )
    meeting_schedule = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Regular meeting days/time, e.g. '2nd Thursdays at 9:30 a.m.'",
    )
    source_url = models.URLField(
        max_length=500,
        help_text="seattle.gov committee page the profile was scraped from.",
    )
    scraped_at = models.DateTimeField(
        auto_now=True,
        help_text="Last time the profile was (re-)scraped.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Committee profile (scraped)"
        verbose_name_plural = "Committee profiles (scraped)"

    def __str__(self):
        return f"Profile for {self.organization}"


class CommitteeSummary(models.Model):
    """LLM-generated "what this committee does and is working on" card for a
    standing council committee. One row per OCD ``Organization`` (committees
    live only in OCD — ``councilmatic_core.Organization`` is empty), keyed by a
    ``OneToOneField`` to ``core.Organization`` like ``RepSummary`` keys to
    ``core.Person``.

    Unlike a bill or event (immutable once it happens), a committee's activity
    evolves, so this summary is *refreshed* when its inputs change rather than
    written once. ``content_hash`` is a digest of the stats snapshot the model
    saw (roster, recent meeting overviews, bills); ``summarize_committees``
    only (re-)submits a committee whose live hash differs from the stored one,
    so unchanged committees don't burn tokens every cycle. ``stats_snapshot``
    keeps the exact input for reproducibility. UPSERT by ``organization_id``."""

    organization = models.OneToOneField(
        "core.Organization",
        on_delete=models.CASCADE,
        related_name="committee_summary",
        help_text="OCD Organization (committee) this summary belongs to.",
    )
    summary = models.TextField(
        help_text="2-3 paragraph plain-prose synthesis: the committee's focus "
        "plus recent activity. Paragraphs joined with '\\n\\n'.",
    )
    stats_snapshot = models.JSONField(
        default=dict,
        help_text="Structured context passed to the model — roster, recent "
        "meeting overviews, bills handled. Reproducibility audit trail.",
    )
    content_hash = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text="SHA-256 of the input signal (bills, meetings, roster). The "
        "command re-summarizes only when the live hash differs from this.",
    )
    model_version = models.CharField(
        max_length=100,
        blank=True,
        default="",
        help_text="Claude model that generated the summary.",
    )
    summary_batch_id = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text="Anthropic Message Batches ID this summary came from. "
        "Empty for synchronous one-off retries.",
    )
    generated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last time the summary was (re-)generated.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Committee LLM Summary"
        verbose_name_plural = "Committee LLM Summaries"

    def __str__(self):
        return f"Summary for {self.organization}"


class SeattleBill(Bill):
    """
    Extend the base Bill model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True

    def __str__(self):
        return self.friendly_name or self.identifier


class SeattleEvent(Event):
    """
    Extend the base Event model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True


class SeattlePerson(Person):
    """
    Extend the base Person model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """
    
    class Meta:
        proxy = True


class SeattleOrganization(Organization):
    """
    Extend the base Organization model for city-specific functionality.
    Add any custom fields or methods specific to your city here.
    """

    class Meta:
        proxy = True


class ZoningPolygon(models.Model):
    """
    One polygon feature from Seattle SDCI's Land Use Zoning layer
    (Zoned_Development_Capacity_Layers_2016 FeatureServer layer 9).

    2,600+ polygons covering the entire city. `zoning` is the fully-
    qualified designation including modifiers (e.g., 'NC3-65'); `base_zone`
    is the FK to the base ZoningCode ('NC3') matching our legend table.
    Use this model as the spatial backbone: intersect with landmarks,
    council districts, or bill-referenced addresses.
    """
    object_id = models.IntegerField(
        unique=True,
        help_text="SDCI FeatureServer OBJECTID — identity key for upsert"
    )
    zone_id = models.IntegerField(
        db_index=True,
        help_text="SDCI ZONEID"
    )
    zoning = models.CharField(
        max_length=50,
        db_index=True,
        help_text="Full designation including modifiers (e.g., 'NC3-65')"
    )
    base_zone = models.ForeignKey(
        "ZoningCode",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="polygons",
        help_text="FK to the base zone legend entry; null if ZONELUT is not in our legend"
    )
    contract = models.CharField(max_length=40, blank=True)
    ordinance_number = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Ordinance that created/amended this zone"
    )
    effective_date = models.DateField(null=True, blank=True)
    historic = models.CharField(max_length=100, blank=True)
    pedestrian_overlay = models.CharField(max_length=100, blank=True)
    shoreline_overlay = models.CharField(max_length=100, blank=True)
    other_overlay = models.CharField(max_length=100, blank=True)
    lightrail_overlay = models.CharField(max_length=100, blank=True)
    previous_zone_id = models.IntegerField(null=True, blank=True)
    special_area_id = models.CharField(max_length=30, blank=True)
    boundary = gis_models.MultiPolygonField(srid=4326)
    source_url = models.URLField(max_length=500, blank=True)
    ingested_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["zoning", "object_id"]
        verbose_name = "Zoning Polygon"
        verbose_name_plural = "Zoning Polygons"

    def __str__(self):
        return f"{self.zoning} (#{self.object_id})"


class ZoningCode(models.Model):
    """
    One row of the Seattle zoning-district legend (e.g., 'NR1' → 'Residential,
    Neighborhood 1'). Parsed from the KEY TO DISTRICT DESIGNATIONS page of
    the SMC PDF.
    """
    abbreviation = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text="Zone code shown on maps (e.g., 'NR1')"
    )
    name = models.CharField(
        max_length=200,
        help_text="Full district name (e.g., 'Residential, Neighborhood 1')"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["abbreviation"]
        verbose_name = "Zoning Code"
        verbose_name_plural = "Zoning Codes"

    def __str__(self):
        return f"{self.abbreviation} — {self.name}"


class HistoricLandmark(models.Model):
    """
    A designated Seattle historic landmark. Ingested from SDCI's Landmarks
    FeatureServer (data-seattlecitygis.opendata.arcgis.com) — a point layer
    of ~500 landmarks with coordinates, ordinance numbers, designation
    documents, and photos.

    designation_type / designation_type_name capture the Roman-numeral
    grouping from SMC Ch. 25.32's PDF tables (I Residences, II Buildings,
    etc.) — nullable because the GIS source doesn't expose the grouping.
    Backfill from the PDF if a concrete use case emerges.
    """
    landmark_number = models.IntegerField(
        unique=True,
        null=True,
        blank=True,
        db_index=True,
        help_text="SDCI's stable landmark sequence ID (LANDNO); upsert key. "
                  "Nullable in the DB because Postgres permits multiple NULLs "
                  "under a unique index; the ingestion command enforces presence."
    )
    designation_type = models.CharField(
        max_length=10,
        blank=True,
        db_index=True,
        help_text="Roman numeral category code (I–IX); blank if unknown"
    )
    designation_type_name = models.CharField(
        max_length=60,
        blank=True,
        help_text="Human label for the category, e.g., 'Residences'"
    )
    name = models.CharField(
        max_length=300,
        db_index=True
    )
    address = models.CharField(
        max_length=500,
        blank=True
    )
    original_address = models.CharField(
        max_length=500,
        blank=True,
        help_text="Original address, if the landmark has since been renamed/readdressed"
    )
    designating_ord_number = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="Ordinance that designated this landmark"
    )
    designation_date = models.DateField(
        null=True,
        blank=True,
        help_text="Effective date of designation (EFF_DATE in SDCI)"
    )
    photo_filename = models.CharField(
        max_length=300,
        blank=True,
        help_text="Filename of the landmark photo on Seattle.gov"
    )
    document_filename = models.CharField(
        max_length=300,
        blank=True,
        help_text="Filename of the designation report PDF on Seattle.gov"
    )
    geolocation = gis_models.PointField(
        srid=4326,
        null=True,
        blank=True,
        help_text="Point from SDCI's GIS layer (WGS84)"
    )
    council_district = models.ForeignKey(
        "reps.District",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="historic_landmarks",
        help_text="District resolved by point-in-polygon against geolocation"
    )
    source_url = models.URLField(
        max_length=500,
        blank=True
    )
    scraped_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["designation_type", "name"]
        verbose_name = "Historic Landmark"
        verbose_name_plural = "Historic Landmarks"

    def __str__(self):
        return f"{self.name} ({self.designation_type_name})"


class OrdinanceCodification(models.Model):
    """
    A row from the SMC's Table of Ordinances Codified (pp. 4397+ in the
    PDF), mapping one ordinance number to a human-readable description
    of what it did, plus the SMC chapter/section refs extracted from
    that description.
    """
    ordinance_number = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text="May be 'I-137' (initiative) or similar, not just numeric"
    )
    description = models.TextField(
        blank=True,
        help_text="Raw description text from the TOC row (e.g., "
                  "'Amends §§ 23.45.010, 23.45.020; adds § 23.45.025')"
    )
    adopted_date = models.DateField(
        null=True,
        blank=True,
        help_text="Adoption date if sourced from elsewhere; the PDF TOC lists only ord numbers"
    )
    codified_sections = models.JSONField(
        default=list,
        help_text="Chapter/section refs extracted from the description, e.g., "
                  "['23.45.010', '23.45.020', '25.32']"
    )
    source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where this row was extracted"
    )
    source_url = models.URLField(
        max_length=500,
        blank=True
    )
    scraped_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        ordering = ["-adopted_date", "ordinance_number"]
        verbose_name = "Ordinance Codification"
        verbose_name_plural = "Ordinance Codifications"

    def __str__(self):
        return f"Ord. {self.ordinance_number}"


class HistoricReviewDistrict(models.Model):
    """
    A Seattle historic or special-review overlay district. Eight of these
    cover specific neighborhoods (Pioneer Square, International District,
    Ballard Avenue, etc.) and impose additional design-review requirements
    on construction and alteration. Ingested from SDCI's 'Historic and
    Special Review Districts' polygon layer.
    """
    object_id = models.IntegerField(
        unique=True,
        db_index=True,
        help_text="SDCI FeatureServer OBJECTID — upsert key"
    )
    overlay_code = models.CharField(
        max_length=10,
        unique=True,
        db_index=True,
        help_text="Short code (e.g., 'ID', 'BD', 'PS')"
    )
    name = models.CharField(
        max_length=200,
        help_text="Full district name (e.g., 'Ballard Avenue Landmark District')"
    )
    purpose = models.TextField(
        blank=True,
        help_text="Purpose/preamble text from SDCI's public description"
    )
    district_type = models.CharField(
        max_length=20,
        db_index=True,
        help_text="'HISTORIC' for landmark districts, 'OVERLAY' for special review"
    )
    smc_chapter = models.CharField(
        max_length=20,
        blank=True,
        db_index=True,
        help_text="SMC chapter that governs this district (e.g., '25.16'), "
                  "the 'Chapter ' prefix stripped for queryability"
    )
    chapter_link = models.URLField(
        max_length=500,
        blank=True,
        help_text="Municode URL to the governing SMC chapter"
    )
    boundary = gis_models.MultiPolygonField(srid=4326)
    source_url = models.URLField(max_length=500, blank=True)
    ingested_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["district_type", "name"]
        verbose_name = "Historic/Review District"
        verbose_name_plural = "Historic/Review Districts"

    def __str__(self):
        return self.name


class SectionOrdinanceRef(models.Model):
    """
    One revision parenthetical from a section's full_text. A section may
    have many (one per amending ordinance). Populated during PDF parsing,
    not by a separate scraper — the source is already in MunicipalCodeSection.
    """
    section = models.ForeignKey(
        MunicipalCodeSection,
        on_delete=models.CASCADE,
        related_name="ordinance_refs"
    )
    ordinance_number = models.CharField(
        max_length=20,
        db_index=True
    )
    ordinance_year = models.IntegerField(
        null=True,
        blank=True
    )
    section_reference = models.CharField(
        max_length=20,
        blank=True,
        help_text="Subsection within the ordinance, e.g., '§ 1'"
    )

    class Meta:
        ordering = ["section", "ordinance_year", "ordinance_number"]
        unique_together = ["section", "ordinance_number", "section_reference"]
        verbose_name = "Section Ordinance Reference"
        verbose_name_plural = "Section Ordinance References"

    def __str__(self):
        return f"{self.section.section_number} ← Ord. {self.ordinance_number}"


class Subchapter(models.Model):
    """
    A subchapter within an SMC chapter (e.g., Ch. 25.05 Subchapter IX
    "Categorical Exemptions"). Populated by parse_smc_pdf from two sources:

      - Official: scraped from the chapter's table of contents at the
        start of the chapter in the PDF. Authoritative section list.
      - Synthesized: reconstructed from body-divider lines
        ("Subchapter <Roman> <Name>") when no TOC was found for the
        chapter. Section list inferred from parse emissions.

    declared_section_numbers is the TOC-asserted section list for this
    subchapter. Comparing it to sections.values_list('section_number') at
    validation time surfaces parse regressions (either a section the TOC
    claims but the body parse missed, or a section parsed but not listed
    in the TOC). Mismatches are recorded as ParseValidationIssue rows.
    """
    SOURCE_OFFICIAL = "official"
    SOURCE_SYNTHESIZED = "synthesized"
    SOURCE_CHOICES = [
        (SOURCE_OFFICIAL, "Official (from PDF TOC)"),
        (SOURCE_SYNTHESIZED, "Synthesized (from body parse)"),
    ]

    chapter_number = models.CharField(
        max_length=20,
        db_index=True,
        help_text="Parent chapter number, e.g., '25.05'"
    )
    roman = models.CharField(
        max_length=10,
        help_text="Roman numeral as printed, e.g., 'IX'"
    )
    ordinal = models.PositiveSmallIntegerField(
        help_text="Integer equivalent of roman (IX -> 9). Used for ORDER BY."
    )
    name = models.CharField(
        max_length=200,
        blank=True,
        help_text="Subchapter name, e.g., 'Categorical Exemptions'. "
                  "Blank when the divider is bare 'Subchapter <Roman>'."
    )
    toc_source = models.CharField(
        max_length=20,
        choices=SOURCE_CHOICES,
        help_text="Whether declared_section_numbers came from an official "
                  "PDF TOC or was synthesized from body parse emissions."
    )
    toc_source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where the TOC entry for this subchapter was parsed."
    )
    body_source_pdf_page = models.IntegerField(
        null=True,
        blank=True,
        help_text="PDF page where the in-body 'Subchapter <Roman> <Name>' "
                  "divider appears."
    )
    declared_section_numbers = models.JSONField(
        default=list,
        help_text="Section numbers declared under this subchapter in the "
                  "TOC, in document order, e.g., ['25.05.800', '25.05.810']."
    )

    class Meta:
        ordering = ["chapter_number", "ordinal"]
        unique_together = ["chapter_number", "roman"]
        verbose_name = "Subchapter"
        verbose_name_plural = "Subchapters"

    def __str__(self):
        label = f"{self.chapter_number} Subchapter {self.roman}"
        return f"{label}: {self.name}" if self.name else label


class ParseValidationIssue(models.Model):
    """
    A parse-time discrepancy between what a TOC declares and what the body
    pass actually emitted. Written by parse_smc_pdf's validation step and
    overwritten on every run (old rows deleted, new ones recorded).

    The parser never fails on a mismatch — these rows are the audit trail
    so regressions are visible without blocking ingest.
    """
    CAT_MISSING_FROM_BODY = "missing_from_body"
    CAT_UNDECLARED_IN_TOC = "undeclared_in_toc"
    CATEGORY_CHOICES = [
        (CAT_MISSING_FROM_BODY, "Declared in TOC but not emitted by body parse"),
        (CAT_UNDECLARED_IN_TOC, "Emitted by body parse but not declared in TOC"),
    ]

    subchapter = models.ForeignKey(
        Subchapter,
        on_delete=models.CASCADE,
        related_name="validation_issues"
    )
    category = models.CharField(
        max_length=32,
        choices=CATEGORY_CHOICES,
        db_index=True
    )
    section_number = models.CharField(
        max_length=32,
        blank=True,
        help_text="The section this issue concerns, if any."
    )
    message = models.TextField(
        blank=True,
        help_text="Free-form description of the issue."
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["subchapter", "category", "section_number"]
        verbose_name = "Parse Validation Issue"
        verbose_name_plural = "Parse Validation Issues"

    def __str__(self):
        return f"[{self.category}] {self.subchapter} — {self.section_number}"


class PipelineRun(models.Model):
    """One row per scheduled pipeline invocation (a cron cycle) — the parent
    that groups the several Anthropic batches a single run submits.

    The scheduler fires ``update_seattle.sh`` (a full cycle) and
    ``poll_llm_batches.sh`` (an offset drain) on a 6h cadence; each calls
    multiple Batch management commands, every one of which submits its own
    Anthropic batch. ``PipelineRun`` is the internal handle that ties those
    together: the dashboard groups a cycle's work under one ``run_key``, and
    the heartbeat alert ("no successful run in > N hours") queries this table.

    ``run_key`` is a readable, sortable id minted by the orchestration
    (``run_<UTC-ISO>``, e.g. ``run_20260604T0000Z``) and propagated to each
    command via the ``PIPELINE_RUN_KEY`` env var, so all commands in a cycle
    attach to the same row. A one-off ``manage.py`` invocation with no env key
    mints its own ``kind="manual"`` run, so ad-hoc work is still tracked.

    Correlation: ``run_key`` is also stamped on every flat-log line (#205), so
    a row here joins to the deep-debug log both ways."""

    KIND_FULL_CYCLE = "full-cycle"
    KIND_OFFSET_DRAIN = "offset-drain"
    KIND_WEEKLY_REP = "weekly-rep"
    KIND_MANUAL = "manual"
    KIND_CHOICES = [
        (KIND_FULL_CYCLE, "Full cycle (scrape + extract + drain + submit)"),
        (KIND_OFFSET_DRAIN, "Offset drain pass"),
        (KIND_WEEKLY_REP, "Weekly rep refresh"),
        (KIND_MANUAL, "Manual / ad-hoc invocation"),
    ]

    STATUS_RUNNING = "running"
    STATUS_SUCCESS = "success"
    STATUS_FAILED = "failed"
    STATUS_CHOICES = [
        (STATUS_RUNNING, "Running"),
        (STATUS_SUCCESS, "Success"),
        (STATUS_FAILED, "Failed"),
    ]

    run_key = models.CharField(
        max_length=64,
        unique=True,
        help_text="Readable, sortable internal run id, e.g. 'run_20260604T0000Z'.",
    )
    kind = models.CharField(max_length=20, choices=KIND_CHOICES, db_index=True)
    status = models.CharField(
        max_length=12,
        choices=STATUS_CHOICES,
        default=STATUS_RUNNING,
        db_index=True,
        help_text=(
            "Set to success/failed when the run finishes; a row stuck on "
            "'running' flags a crashed cycle (the heartbeat alert keys off this)."
        ),
    )
    started_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the run completed; null while still running.",
    )

    class Meta:
        ordering = ["-started_at"]
        verbose_name = "Pipeline Run"
        verbose_name_plural = "Pipeline Runs"

    def __str__(self):
        return f"{self.run_key} ({self.kind}, {self.status})"


class BatchRun(models.Model):
    """One row per Anthropic Message Batch submitted by a Batch command — the
    durable, queryable replacement for the old ``data/*_state.json`` state
    files, and the store the drain-then-submit state machine reads.

    Each of the four Batch commands (``tag_bill_issue_areas``,
    ``summarize_legislation``, ``summarize_events``, ``summarize_reps``) submits
    one batch per run. "Is there an in-flight batch for this command?" — the
    question the state machine asks every run — becomes a query here
    (``status in (submitted, in_progress)``) instead of reading a JSON file, so
    state survives container recreates / deploys.

    Drain-then-submit means a batch is *submitted* in one ``PipelineRun`` and
    usually *drained* in a later one, hence the two run FKs: ``submitted_in_run``
    and ``processed_in_run`` (null until drained). Both are ``SET_NULL`` so
    pruning old runs never destroys batch history.

    ``batch_id`` (the Anthropic ``msgbatch_…``) is also printed on the flat
    log's submit/drain lines (#205), so a row joins to the deep-debug log."""

    COMMAND_CHOICES = [
        ("tag_bill_issue_areas", "tag_bill_issue_areas"),
        ("summarize_legislation", "summarize_legislation"),
        ("summarize_events", "summarize_events"),
        ("summarize_reps", "summarize_reps"),
        ("summarize_committees", "summarize_committees"),
    ]

    STATUS_SUBMITTED = "submitted"
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_ENDED = "ended"
    STATUS_PROCESSED = "processed"
    STATUS_FAILED = "failed"
    STATUS_CHOICES = [
        (STATUS_SUBMITTED, "Submitted"),
        (STATUS_IN_PROGRESS, "In progress"),
        (STATUS_ENDED, "Ended (awaiting processing)"),
        (STATUS_PROCESSED, "Processed (results persisted)"),
        (STATUS_FAILED, "Failed / expired"),
    ]

    command = models.CharField(
        max_length=64,
        choices=COMMAND_CHOICES,
        db_index=True,
        help_text="The management command that submitted this batch.",
    )
    batch_id = models.CharField(
        max_length=64,
        db_index=True,
        help_text="Anthropic Message Batches id (msgbatch_…).",
    )
    model = models.CharField(
        max_length=100,
        help_text="Claude model the batch was submitted with.",
    )
    status = models.CharField(
        max_length=12,
        choices=STATUS_CHOICES,
        default=STATUS_SUBMITTED,
        db_index=True,
    )
    item_count = models.PositiveIntegerField(
        help_text="Number of requests in the batch (bills / events / reps).",
    )
    success_count = models.PositiveIntegerField(null=True, blank=True)
    error_count = models.PositiveIntegerField(null=True, blank=True)
    errors = models.JSONField(
        default=list,
        help_text="First N (item_id, message) failures from processing.",
    )
    submitted_at = models.DateTimeField(auto_now_add=True)
    processed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When results were polled + persisted; null until drained.",
    )
    submitted_in_run = models.ForeignKey(
        PipelineRun,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="submitted_batches",
        help_text="The run that submitted this batch.",
    )
    processed_in_run = models.ForeignKey(
        PipelineRun,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="drained_batches",
        help_text="The run that drained + persisted this batch (often a later cycle).",
    )
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-submitted_at"]
        verbose_name = "Batch Run"
        verbose_name_plural = "Batch Runs"

    def __str__(self):
        return f"{self.command} {self.batch_id} ({self.status})"


class PipelineStep(models.Model):
    """One row per step within a ``PipelineRun`` — the scrape, sync, extraction,
    and LLM-batch stages a cycle runs in sequence (issue #214). Gives the
    dashboard a per-step timeline (status + duration + output) so a hung scrape
    or a failed extraction is visible, not just the LLM phase. Created by the
    ``run_pipeline`` orchestrator at the top of each step.

    ``output`` is a truncated tail of the step's stdout/stderr — the orchestrator
    tees it, so the full text still reaches the flat log (joined by ``run_key``).
    ``metrics`` holds whatever structured bits a step reports (a subprocess
    returncode today; scrape / extract counts as they're enriched)."""

    STATUS_RUNNING = "running"
    STATUS_SUCCESS = "success"
    STATUS_FAILED = "failed"
    STATUS_SKIPPED = "skipped"
    STATUS_CHOICES = [
        (STATUS_RUNNING, "Running"),
        (STATUS_SUCCESS, "Success"),
        (STATUS_FAILED, "Failed"),
        (STATUS_SKIPPED, "Skipped"),
    ]

    pipeline_run = models.ForeignKey(
        PipelineRun,
        on_delete=models.CASCADE,
        related_name="steps",
        help_text="The cycle this step ran in.",
    )
    name = models.CharField(
        max_length=64,
        db_index=True,
        help_text="Step key, e.g. 'pupa_scrape' / 'extract_transcripts' / 'summarize_events'.",
    )
    ordinal = models.PositiveSmallIntegerField(
        help_text="1-based position of the step within the cycle.",
    )
    status = models.CharField(
        max_length=12,
        choices=STATUS_CHOICES,
        default=STATUS_RUNNING,
        db_index=True,
    )
    started_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the step finished; null while still running.",
    )
    output = models.TextField(
        blank=True,
        default="",
        help_text=(
            "Truncated tail of the step's stdout/stderr; the full text is in the "
            "flat log, joined by run_key."
        ),
    )
    metrics = models.JSONField(
        default=dict,
        help_text="Structured per-step bits (subprocess returncode, counts).",
    )

    class Meta:
        ordering = ["pipeline_run", "ordinal"]
        verbose_name = "Pipeline Step"
        verbose_name_plural = "Pipeline Steps"

    def __str__(self):
        return f"{self.pipeline_run.run_key} · {self.ordinal}. {self.name} ({self.status})"


class BillTags(models.Model):
    """LLM-assigned issue-area tags for a bill — one row per ``Bill``.

    Tags were originally written to the OCD ``Bill.subject`` ArrayField, but the
    nightly scrape's importer resets ``subject`` to ``[]`` on every re-import
    (the Seattle scraper adds no subjects), wiping them — so the tagger re-tagged
    the same scrape-window bills every cycle (issue #217). Storing them here,
    like the LLM summary models, keeps them scrape-safe. The vocabulary is fixed
    in ``claude_service.BILL_TAG_VOCABULARY``."""

    bill = models.OneToOneField(
        Bill,
        on_delete=models.CASCADE,
        related_name="issue_tags",
        help_text="The bill these issue-area tags describe.",
    )
    tags = ArrayField(
        models.CharField(max_length=64),
        default=list,
        help_text=(
            "1-3 issue-area tags from the controlled vocabulary, ordered by "
            "relevance."
        ),
    )
    model_version = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text="Claude model that produced the tags.",
    )
    tagged_batch_id = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text=(
            "Anthropic Message Batches ID these tags came from. Empty for "
            "synchronous one-off runs."
        ),
    )
    generated_at = models.DateTimeField(auto_now_add=True)
    last_regenerated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Bill Issue Tags"
        verbose_name_plural = "Bill Issue Tags"

    def __str__(self):
        return f"Tags: {self.bill.identifier} {self.tags}"


class PipelineAlertState(models.Model):
    """Singleton that lets ``check_pipeline_health`` email on health transitions
    and periodic re-nags rather than on every tick (#210). One row (pk=1)."""

    healthy = models.BooleanField(
        default=True,
        help_text="Last assessed health (a successful full-cycle within the heartbeat window).",
    )
    last_alerted_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the last alert (or recovery) email was sent.",
    )
    last_checked_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the health check last ran.",
    )
    detail = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Summary of the last assessment.",
    )

    class Meta:
        verbose_name = "Pipeline Alert State"
        verbose_name_plural = "Pipeline Alert State"

    def __str__(self):
        status = "healthy" if self.healthy else "UNHEALTHY"
        return f"{status} (checked {self.last_checked_at})"
