# Generated by Django 4.2.27 on 2026-01-04 22:35

from django.db import migrations


def add_is_current_column(apps, schema_editor):
    """Add is_current column to councilmatic_core_person table"""
    schema_editor.execute(
        """
        ALTER TABLE councilmatic_core_person
        ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT TRUE;
        """
    )
    # Set all existing people to current by default
    schema_editor.execute(
        """
        UPDATE councilmatic_core_person SET is_current = TRUE WHERE is_current IS NULL;
        """
    )


def remove_is_current_column(apps, schema_editor):
    """Remove is_current column from councilmatic_core_person table"""
    schema_editor.execute(
        """
        ALTER TABLE councilmatic_core_person DROP COLUMN IF EXISTS is_current;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '__latest__'),
    ]

    operations = [
        migrations.RunPython(add_is_current_column, remove_is_current_column),
    ]