from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0001_add_is_current_to_person'),
        ('councilmatic_core', '0053_add_councilmatic_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalCodeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(help_text="SMC title number (e.g., '23' for Land Use Code)", max_length=10)),
                ('chapter_number', models.CharField(blank=True, help_text="Chapter number (e.g., '23.45')", max_length=20)),
                ('section_number', models.CharField(db_index=True, help_text="Full section number (e.g., '23.45.010')", max_length=30)),
                ('title', models.CharField(help_text='Section title/heading', max_length=500)),
                ('full_text', models.TextField(help_text='Full text of this section')),
                ('plain_summary', models.TextField(blank=True, help_text='Plain-English summary generated by LLM')),
                ('summary_model', models.CharField(blank=True, help_text="Model used to generate summary (e.g., 'claude-3-haiku')", max_length=50)),
                ('summary_generated_at', models.DateTimeField(blank=True, help_text='When the summary was generated', null=True)),
                ('source_pdf_page', models.IntegerField(blank=True, help_text='Page number in source PDF', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this section was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Municipal Code Section',
                'verbose_name_plural': 'Municipal Code Sections',
                'ordering': ['title_number', 'chapter_number', 'section_number'],
                'unique_together': {('title_number', 'chapter_number', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='LegislationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Plain-English summary of what this legislation does')),
                ('impact_analysis', models.TextField(blank=True, help_text='Analysis of how this affects current municipal code')),
                ('key_changes', models.JSONField(blank=True, default=list, help_text='Structured list of key changes')),
                ('model_version', models.CharField(help_text="Model used (e.g., 'claude-sonnet-4-20250514')", max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_regenerated', models.DateTimeField(auto_now=True)),
                ('bill', models.OneToOneField(help_text='The legislation being summarized', on_delete=models.deletion.CASCADE, related_name='llm_summary', to='councilmatic_core.bill')),
                ('affected_sections', models.ManyToManyField(blank=True, help_text='Municipal code sections this legislation modifies', related_name='affected_by_legislation', to='seattle_app.municipalcodesection')),
            ],
            options={
                'verbose_name': 'Legislation Summary',
                'verbose_name_plural': 'Legislation Summaries',
            },
        ),
    ]
