# Generated by Django 4.2.27 on 2026-04-23 19:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0053_add_councilmatic_bio'),
        ('core', '0009_auto_20241111_1450'),
        ('seattle_app', '0002_add_llm_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='District number (1–7)')),
                ('name', models.CharField(help_text="Display name, e.g., 'District 1'", max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='District boundary polygon (WGS84)', srid=4326)),
                ('effective_from', models.DateField(help_text='First date this boundary was in effect')),
                ('effective_to', models.DateField(blank=True, help_text='Last date this boundary was in effect; null if current', null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL the shapefile was loaded from', max_length=500)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(blank=True, help_text='Link to the councilmatic/OCD Post representing this seat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_district', to='core.post')),
            ],
            options={
                'verbose_name': 'Council District',
                'verbose_name_plural': 'Council Districts',
                'ordering': ['number', '-effective_from'],
                'unique_together': {('number', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='OrdinanceCodification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinance_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('adopted_date', models.DateField(blank=True, null=True)),
                ('codified_sections', models.JSONField(default=list, help_text="List of SMC section number strings, e.g., ['23.45.010', '23.45.020']")),
                ('source_url', models.URLField(max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordinance Codification',
                'verbose_name_plural': 'Ordinance Codifications',
                'ordering': ['-adopted_date', 'ordinance_number'],
            },
        ),
        migrations.CreateModel(
            name='ZoningMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_code', models.CharField(help_text="Municode identifier, e.g., 'MAP_5'", max_length=30, unique=True)),
                ('map_number', models.IntegerField(db_index=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(blank=True, upload_to='zoning_maps/')),
                ('source_url', models.URLField(max_length=500)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoning Map',
                'verbose_name_plural': 'Zoning Maps',
                'ordering': ['map_number'],
            },
        ),
        migrations.CreateModel(
            name='SeattleBill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='SeattleEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.event',),
        ),
        migrations.CreateModel(
            name='SeattleOrganization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.organization',),
        ),
        migrations.CreateModel(
            name='SeattlePerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('councilmatic_core.person',),
        ),
        migrations.AlterField(
            model_name='legislationsummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='municipalcodesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HistoricLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_type', models.CharField(db_index=True, help_text='Roman numeral category code (I–IX)', max_length=10)),
                ('designation_type_name', models.CharField(help_text="Human label for the category, e.g., 'Residences'", max_length=60)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('designating_ord_number', models.CharField(blank=True, db_index=True, help_text='Ordinance that designated this landmark', max_length=20)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geocoded location; null if geocoding failed or not yet run', null=True, srid=4326)),
                ('source_url', models.URLField(max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('council_district', models.ForeignKey(blank=True, help_text='District resolved by point-in-polygon against geolocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historic_landmarks', to='seattle_app.councildistrict')),
            ],
            options={
                'verbose_name': 'Historic Landmark',
                'verbose_name_plural': 'Historic Landmarks',
                'ordering': ['designation_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectionOrdinanceRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinance_number', models.CharField(db_index=True, max_length=20)),
                ('ordinance_year', models.IntegerField(blank=True, null=True)),
                ('section_reference', models.CharField(blank=True, help_text="Subsection within the ordinance, e.g., '§ 1'", max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinance_refs', to='seattle_app.municipalcodesection')),
            ],
            options={
                'verbose_name': 'Section Ordinance Reference',
                'verbose_name_plural': 'Section Ordinance References',
                'ordering': ['section', 'ordinance_year', 'ordinance_number'],
                'unique_together': {('section', 'ordinance_number', 'section_reference')},
            },
        ),
    ]
