# Generated by Django 4.2.27 on 2026-04-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0003_councildistrict_ordinancecodification_zoningmap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(db_index=True, help_text="Zone code shown on maps (e.g., 'NR1')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Full district name (e.g., 'Residential, Neighborhood 1')", max_length=200)),
                ('source_pdf_page', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zoning Code',
                'verbose_name_plural': 'Zoning Codes',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.AddField(
            model_name='zoningmap',
            name='source_pdf_page',
            field=models.IntegerField(blank=True, help_text='Page in the SMC PDF corresponding to this map', null=True),
        ),
    ]
