# Generated by Django 4.2.27 on 2026-04-23 21:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0004_zoningcode_zoningmap_source_pdf_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoningPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(help_text='SDCI FeatureServer OBJECTID — identity key for upsert', unique=True)),
                ('zone_id', models.IntegerField(db_index=True, help_text='SDCI ZONEID')),
                ('zoning', models.CharField(db_index=True, help_text="Full designation including modifiers (e.g., 'NC3-65')", max_length=50)),
                ('contract', models.CharField(blank=True, max_length=40)),
                ('ordinance_number', models.CharField(blank=True, db_index=True, help_text='Ordinance that created/amended this zone', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('historic', models.CharField(blank=True, max_length=100)),
                ('pedestrian_overlay', models.CharField(blank=True, max_length=100)),
                ('shoreline_overlay', models.CharField(blank=True, max_length=100)),
                ('other_overlay', models.CharField(blank=True, max_length=100)),
                ('lightrail_overlay', models.CharField(blank=True, max_length=100)),
                ('previous_zone_id', models.IntegerField(blank=True, null=True)),
                ('special_area_id', models.CharField(blank=True, max_length=30)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('base_zone', models.ForeignKey(blank=True, help_text='FK to the base zone legend entry; null if ZONELUT is not in our legend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polygons', to='seattle_app.zoningcode')),
            ],
            options={
                'verbose_name': 'Zoning Polygon',
                'verbose_name_plural': 'Zoning Polygons',
                'ordering': ['zoning', 'object_id'],
            },
        ),
    ]
