# Generated by Django 4.2.27 on 2026-04-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0005_zoningpolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoningMap',
        ),
    ]
