# Generated by Django 4.2.27 on 2026-04-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0002_district_description'),
        ('seattle_app', '0006_drop_zoningmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiclandmark',
            name='council_district',
            field=models.ForeignKey(blank=True, help_text='District resolved by point-in-polygon against geolocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historic_landmarks', to='reps.district'),
        ),
        migrations.DeleteModel(
            name='CouncilDistrict',
        ),
    ]
