# Generated by Django 4.2.27 on 2026-04-23 22:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0008_legacy_zoning_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiclandmark',
            name='designation_date',
            field=models.DateField(blank=True, help_text='Effective date of designation (EFF_DATE in SDCI)', null=True),
        ),
        migrations.AddField(
            model_name='historiclandmark',
            name='document_filename',
            field=models.CharField(blank=True, help_text='Filename of the designation report PDF on Seattle.gov', max_length=300),
        ),
        migrations.AddField(
            model_name='historiclandmark',
            name='landmark_number',
            field=models.IntegerField(blank=True, db_index=True, help_text="SDCI's stable landmark sequence ID (LANDNO); upsert key. Nullable in the DB because Postgres permits multiple NULLs under a unique index; the ingestion command enforces presence.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historiclandmark',
            name='original_address',
            field=models.CharField(blank=True, help_text='Original address, if the landmark has since been renamed/readdressed', max_length=500),
        ),
        migrations.AddField(
            model_name='historiclandmark',
            name='photo_filename',
            field=models.CharField(blank=True, help_text='Filename of the landmark photo on Seattle.gov', max_length=300),
        ),
        migrations.AlterField(
            model_name='historiclandmark',
            name='designation_type',
            field=models.CharField(blank=True, db_index=True, help_text='Roman numeral category code (I–IX); blank if unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='historiclandmark',
            name='designation_type_name',
            field=models.CharField(blank=True, help_text="Human label for the category, e.g., 'Residences'", max_length=60),
        ),
        migrations.AlterField(
            model_name='historiclandmark',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Point from SDCI's GIS layer (WGS84)", null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='historiclandmark',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
