# Generated by Django 4.2.27 on 2026-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0009_historic_landmark_gis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinancecodification',
            name='description',
            field=models.TextField(blank=True, help_text="Raw description text from the TOC row (e.g., 'Amends §§ 23.45.010, 23.45.020; adds § 23.45.025')"),
        ),
        migrations.AddField(
            model_name='ordinancecodification',
            name='source_pdf_page',
            field=models.IntegerField(blank=True, help_text='PDF page where this row was extracted', null=True),
        ),
        migrations.AlterField(
            model_name='ordinancecodification',
            name='adopted_date',
            field=models.DateField(blank=True, help_text='Adoption date if sourced from elsewhere; the PDF TOC lists only ord numbers', null=True),
        ),
        migrations.AlterField(
            model_name='ordinancecodification',
            name='codified_sections',
            field=models.JSONField(default=list, help_text="Chapter/section refs extracted from the description, e.g., ['23.45.010', '23.45.020', '25.32']"),
        ),
        migrations.AlterField(
            model_name='ordinancecodification',
            name='ordinance_number',
            field=models.CharField(db_index=True, help_text="May be 'I-137' (initiative) or similar, not just numeric", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ordinancecodification',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
