# Generated by Django 4.2.27 on 2026-04-24 01:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0010_ordinance_codification_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricReviewDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, help_text='SDCI FeatureServer OBJECTID — upsert key', unique=True)),
                ('overlay_code', models.CharField(db_index=True, help_text="Short code (e.g., 'ID', 'BD', 'PS')", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Full district name (e.g., 'Ballard Avenue Landmark District')", max_length=200)),
                ('purpose', models.TextField(blank=True, help_text="Purpose/preamble text from SDCI's public description")),
                ('district_type', models.CharField(db_index=True, help_text="'HISTORIC' for landmark districts, 'OVERLAY' for special review", max_length=20)),
                ('smc_chapter', models.CharField(blank=True, db_index=True, help_text="SMC chapter that governs this district (e.g., '25.16'), the 'Chapter ' prefix stripped for queryability", max_length=20)),
                ('chapter_link', models.URLField(blank=True, help_text='Municode URL to the governing SMC chapter', max_length=500)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historic/Review District',
                'verbose_name_plural': 'Historic/Review Districts',
                'ordering': ['district_type', 'name'],
            },
        ),
    ]
