# Generated by Django 4.2.27 on 2026-04-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0011_historic_review_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subchapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(db_index=True, help_text="Parent chapter number, e.g., '25.05'", max_length=20)),
                ('roman', models.CharField(help_text="Roman numeral as printed, e.g., 'IX'", max_length=10)),
                ('ordinal', models.PositiveSmallIntegerField(help_text='Integer equivalent of roman (IX -> 9). Used for ORDER BY.')),
                ('name', models.CharField(blank=True, help_text="Subchapter name, e.g., 'Categorical Exemptions'. Blank when the divider is bare 'Subchapter <Roman>'.", max_length=200)),
                ('toc_source', models.CharField(choices=[('official', 'Official (from PDF TOC)'), ('synthesized', 'Synthesized (from body parse)')], help_text='Whether declared_section_numbers came from an official PDF TOC or was synthesized from body parse emissions.', max_length=20)),
                ('toc_source_pdf_page', models.IntegerField(blank=True, help_text='PDF page where the TOC entry for this subchapter was parsed.', null=True)),
                ('body_source_pdf_page', models.IntegerField(blank=True, help_text="PDF page where the in-body 'Subchapter <Roman> <Name>' divider appears.", null=True)),
                ('declared_section_numbers', models.JSONField(default=list, help_text="Section numbers declared under this subchapter in the TOC, in document order, e.g., ['25.05.800', '25.05.810'].")),
            ],
            options={
                'verbose_name': 'Subchapter',
                'verbose_name_plural': 'Subchapters',
                'ordering': ['chapter_number', 'ordinal'],
                'unique_together': {('chapter_number', 'roman')},
            },
        ),
        migrations.CreateModel(
            name='ParseValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('missing_from_body', 'Declared in TOC but not emitted by body parse'), ('undeclared_in_toc', 'Emitted by body parse but not declared in TOC')], db_index=True, max_length=32)),
                ('section_number', models.CharField(blank=True, help_text='The section this issue concerns, if any.', max_length=32)),
                ('message', models.TextField(blank=True, help_text='Free-form description of the issue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='seattle_app.subchapter')),
            ],
            options={
                'verbose_name': 'Parse Validation Issue',
                'verbose_name_plural': 'Parse Validation Issues',
                'ordering': ['subchapter', 'category', 'section_number'],
            },
        ),
        migrations.AddField(
            model_name='municipalcodesection',
            name='subchapter',
            field=models.ForeignKey(blank=True, help_text="Subchapter grouping within the chapter, if any. Populated during PDF parse when a 'Subchapter <Roman>' divider is encountered.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='seattle_app.subchapter'),
        ),
    ]
