# Generated by Django 4.2.27 on 2026-04-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0012_subchapter_parsevalidationissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(db_index=True, help_text="SMC title number this appendix attaches to (e.g., '15')", max_length=10)),
                ('label', models.CharField(help_text="Roman-numeral label as it appears in the heading (e.g., 'I', 'I AND II')", max_length=20)),
                ('full_text', models.TextField(help_text='Body text of the appendix')),
                ('source_pdf_page', models.IntegerField(blank=True, help_text='Page number where the appendix heading appears in the source PDF', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Title Appendix',
                'verbose_name_plural': 'Title Appendices',
                'ordering': ['title_number', 'label'],
                'unique_together': {('title_number', 'label')},
            },
        ),
    ]
