# Generated by Django 4.2.30 on 2026-04-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0015_pg_trgm_section_number_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(help_text="Chapter number, e.g. '23.47A'", max_length=20, unique=True)),
                ('title_number', models.CharField(db_index=True, help_text="Parent title number, e.g. '23'", max_length=10)),
                ('name', models.CharField(help_text='Chapter name as printed in the TOC', max_length=300)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code Chapter',
                'verbose_name_plural': 'Code Chapters',
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='CodeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(help_text="SMC title number, e.g. '23' or '12A'", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Title name as printed in the TOC, e.g. 'LAND USE CODE'", max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code Title',
                'verbose_name_plural': 'Code Titles',
                'ordering': ['title_number'],
            },
        ),
    ]
