# Generated by Django 4.2.30 on 2026-05-16 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Pinned to 0053 (the latest councilmatic_core migration that
        # exists in both prod's and dev's installed package versions).
        # makemigrations originally emitted a 0054 dep because the dev
        # container had pulled a newer 5.x-branch zip than prod did at
        # build time. requirements.txt pins django-councilmatic to the
        # 5.x branch URL rather than a specific commit, so each `docker
        # compose ... build` can pull a different snapshot. See the
        # follow-up issue on pinning to a commit instead of a branch.
        ('councilmatic_core', '0053_add_councilmatic_bio'),
        ('seattle_app', '0022_delete_stale_midnight_event_duplicates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipalcodesection',
            options={'base_manager_name': 'objects', 'ordering': ['title_number', 'chapter_number', 'section_number'], 'verbose_name': 'Municipal Code Section', 'verbose_name_plural': 'Municipal Code Sections'},
        ),
        migrations.AlterField(
            model_name='legislationsummary',
            name='summary_batch_id',
            field=models.CharField(blank=True, help_text="Anthropic Message Batches ID this summary came from (e.g., 'msgbatch_01PCxUY7AHperTdVueAxmYr7'). Empty for synchronous one-off generations.", max_length=64),
        ),
        migrations.AlterField(
            model_name='municipalcodesection',
            name='summary_batch_id',
            field=models.CharField(blank=True, help_text="Anthropic Message Batches ID this summary came from (e.g., 'msgbatch_01PCxUY7AHperTdVueAxmYr7'). Empty for synchronous one-off generations or legacy rows.", max_length=64),
        ),
        migrations.CreateModel(
            name='EventTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srt_raw', models.TextField(help_text='Raw SRT as downloaded from Seattle Channel.')),
                ('transcript_text', models.TextField(help_text="Flattened plain text of the SRT (timestamps + sequence numbers stripped, HTML entities decoded). Speaker-turn markers '>>' preserved for chunkability.")),
                ('chapter_markers', models.JSONField(default=list, help_text='Ordered list of {label, start_seconds} dicts from the Seattle Channel agenda-index UI. Empty when a meeting had no marked chapters.')),
                ('source_url', models.URLField(help_text='Seattle Channel URL the SRT was downloaded from.', max_length=500)),
                ('video_url', models.URLField(blank=True, default='', help_text='video.seattle.gov MP4 URL for the meeting. Captured for future Whisper re-transcription; not used by the v1 SRT-based summarizer.', max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(help_text='The council meeting this transcript belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='councilmatic_core.event')),
            ],
            options={
                'verbose_name': 'Event Transcript',
                'verbose_name_plural': 'Event Transcripts',
            },
        ),
    ]
