# Generated by Django 4.2.30 on 2026-05-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Pinned to 0053 to match upstream. See PR #188 / WORK_LOG
        # convention: dev's container has a phantom `0054` that doesn't
        # exist upstream; `makemigrations` keeps emitting it as a dep
        # until dev is rebuilt against the pinned commit. Manually
        # downshift to 0053 for prod safety.
        ('councilmatic_core', '0053_add_councilmatic_bio'),
        ('seattle_app', '0023_eventtranscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(help_text='2-4 paragraph plain-prose meeting overview.')),
                ('item_summaries', models.JSONField(default=list, help_text='Per-agenda-item summaries: list of {label, start_seconds, summary} dicts ordered by time.')),
                ('stats_snapshot', models.JSONField(default=dict, help_text='Structured prompt context passed to the LLM — agenda items, councilmember roster, validated chapter list. Reproducibility audit trail.')),
                ('model_version', models.CharField(blank=True, default='', help_text='Claude model that generated the summary.', max_length=100)),
                ('summary_batch_id', models.CharField(blank=True, default='', help_text='Anthropic Message Batches ID this summary came from. Empty for synchronous one-off retries.', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time the summary was (re-)generated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(help_text='The council meeting this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='llm_summary', to='councilmatic_core.event')),
            ],
            options={
                'verbose_name': 'Event LLM Summary',
                'verbose_name_plural': 'Event LLM Summaries',
            },
        ),
    ]
