# Generated by Django 4.2.30 on 2026-06-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0024_eventsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(help_text="Readable, sortable internal run id, e.g. 'run_20260604T0000Z'.", max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('full-cycle', 'Full cycle (scrape + extract + drain + submit)'), ('offset-drain', 'Offset drain pass'), ('weekly-rep', 'Weekly rep refresh'), ('manual', 'Manual / ad-hoc invocation')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', help_text="Set to success/failed when the run finishes; a row stuck on 'running' flags a crashed cycle (the heartbeat alert keys off this).", max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the run completed; null while still running.', null=True)),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('tag_bill_issue_areas', 'tag_bill_issue_areas'), ('summarize_legislation', 'summarize_legislation'), ('summarize_events', 'summarize_events'), ('summarize_reps', 'summarize_reps')], db_index=True, help_text='The management command that submitted this batch.', max_length=64)),
                ('batch_id', models.CharField(db_index=True, help_text='Anthropic Message Batches id (msgbatch_…).', max_length=64)),
                ('model', models.CharField(help_text='Claude model the batch was submitted with.', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In progress'), ('ended', 'Ended (awaiting processing)'), ('processed', 'Processed (results persisted)'), ('failed', 'Failed / expired')], db_index=True, default='submitted', max_length=12)),
                ('item_count', models.PositiveIntegerField(help_text='Number of requests in the batch (bills / events / reps).')),
                ('success_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(blank=True, null=True)),
                ('errors', models.JSONField(default=list, help_text='First N (item_id, message) failures from processing.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When results were polled + persisted; null until drained.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_in_run', models.ForeignKey(blank=True, help_text='The run that drained + persisted this batch (often a later cycle).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drained_batches', to='seattle_app.pipelinerun')),
                ('submitted_in_run', models.ForeignKey(blank=True, help_text='The run that submitted this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_batches', to='seattle_app.pipelinerun')),
            ],
            options={
                'verbose_name': 'Batch Run',
                'verbose_name_plural': 'Batch Runs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
