# Generated by Django 4.2.30 on 2026-06-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0025_pipeline_run_batch_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Step key, e.g. 'pupa_scrape' / 'extract_transcripts' / 'summarize_events'.", max_length=64)),
                ('ordinal', models.PositiveSmallIntegerField(help_text='1-based position of the step within the cycle.')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the step finished; null while still running.', null=True)),
                ('output', models.TextField(blank=True, default='', help_text="Truncated tail of the step's stdout/stderr; the full text is in the flat log, joined by run_key.")),
                ('metrics', models.JSONField(default=dict, help_text='Structured per-step bits (subprocess returncode, counts).')),
                ('pipeline_run', models.ForeignKey(help_text='The cycle this step ran in.', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='seattle_app.pipelinerun')),
            ],
            options={
                'verbose_name': 'Pipeline Step',
                'verbose_name_plural': 'Pipeline Steps',
                'ordering': ['pipeline_run', 'ordinal'],
            },
        ),
    ]
