# Generated by Django 4.2.30 on 2026-06-05, dependency hand-pinned (see below).

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def _backfill_tags(apps, schema_editor):
    """Best-effort copy of existing ``Bill.subject`` tags into ``BillTags`` so
    the cutover doesn't re-tag the whole corpus once (#217). Most bills' tags
    are still on ``subject`` (only the scrape-window set churns), so this keeps
    them. Wrapped so a failure can NEVER block the deploy — worst case the next
    tag run repopulates ``BillTags``."""
    try:
        Bill = apps.get_model("councilmatic_core", "Bill")
        BillTags = apps.get_model("seattle_app", "BillTags")
        rows = [
            BillTags(bill_id=pk, tags=list(subject))
            for pk, subject in (
                Bill.objects.exclude(subject=[]).values_list("pk", "subject")
            )
            if subject
        ]
        BillTags.objects.bulk_create(rows, batch_size=500, ignore_conflicts=True)
    except Exception:
        pass


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        # Pinned to 0053 (the real upstream latest), NOT dev's phantom
        # `0054_bill_tags` — makemigrations keeps emitting that against the dev
        # container until it's rebuilt against the pinned councilmatic_core
        # commit. Downshift for prod safety. See migration 0024 / PR #188.
        ('councilmatic_core', '0053_add_councilmatic_bio'),
        ('seattle_app', '0026_pipeline_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, help_text='1-3 issue-area tags from the controlled vocabulary, ordered by relevance.', size=None)),
                ('model_version', models.CharField(blank=True, default='', help_text='Claude model that produced the tags.', max_length=50)),
                ('tagged_batch_id', models.CharField(blank=True, default='', help_text='Anthropic Message Batches ID these tags came from. Empty for synchronous one-off runs.', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_regenerated', models.DateTimeField(auto_now=True)),
                ('bill', models.OneToOneField(help_text='The bill these issue-area tags describe.', on_delete=django.db.models.deletion.CASCADE, related_name='issue_tags', to='councilmatic_core.bill')),
            ],
            options={
                'verbose_name': 'Bill Issue Tags',
                'verbose_name_plural': 'Bill Issue Tags',
            },
        ),
        migrations.RunPython(_backfill_tags, _noop_reverse),
    ]
