# Generated by Django 4.2.30 on 2026-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0027_bill_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineAlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthy', models.BooleanField(default=True, help_text='Last assessed health (a successful full-cycle within the heartbeat window).')),
                ('last_alerted_at', models.DateTimeField(blank=True, help_text='When the last alert (or recovery) email was sent.', null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='When the health check last ran.', null=True)),
                ('detail', models.CharField(blank=True, default='', help_text='Summary of the last assessment.', max_length=255)),
            ],
            options={
                'verbose_name': 'Pipeline Alert State',
                'verbose_name_plural': 'Pipeline Alert State',
            },
        ),
    ]
