# Generated by Django 4.2.30 on 2026-06-07 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241111_1450'),
        ('seattle_app', '0028_pipeline_alert_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrun',
            name='command',
            field=models.CharField(choices=[('tag_bill_issue_areas', 'tag_bill_issue_areas'), ('summarize_legislation', 'summarize_legislation'), ('summarize_events', 'summarize_events'), ('summarize_reps', 'summarize_reps'), ('summarize_committees', 'summarize_committees')], db_index=True, help_text='The management command that submitted this batch.', max_length=64),
        ),
        migrations.CreateModel(
            name='CommitteeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text="2-3 paragraph plain-prose synthesis: the committee's focus plus recent activity. Paragraphs joined with '\\n\\n'.")),
                ('stats_snapshot', models.JSONField(default=dict, help_text='Structured context passed to the model — roster, recent meeting overviews, bills handled. Reproducibility audit trail.')),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA-256 of the input signal (bills, meetings, roster). The command re-summarizes only when the live hash differs from this.', max_length=64)),
                ('model_version', models.CharField(blank=True, default='', help_text='Claude model that generated the summary.', max_length=100)),
                ('summary_batch_id', models.CharField(blank=True, default='', help_text='Anthropic Message Batches ID this summary came from. Empty for synchronous one-off retries.', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Last time the summary was (re-)generated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(help_text='OCD Organization (committee) this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='committee_summary', to='core.organization')),
            ],
            options={
                'verbose_name': 'Committee LLM Summary',
                'verbose_name_plural': 'Committee LLM Summaries',
            },
        ),
        migrations.CreateModel(
            name='CommitteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField(blank=True, default='', help_text="The committee's scope/remit prose from its seattle.gov 'Committee Scope:' section.")),
                ('meeting_schedule', models.CharField(blank=True, default='', help_text="Regular meeting days/time, e.g. '2nd Thursdays at 9:30 a.m.'", max_length=255)),
                ('source_url', models.URLField(help_text='seattle.gov committee page the profile was scraped from.', max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now=True, help_text='Last time the profile was (re-)scraped.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(help_text='OCD Organization (committee) this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='committee_profile', to='core.organization')),
            ],
            options={
                'verbose_name': 'Committee profile (scraped)',
                'verbose_name_plural': 'Committee profiles (scraped)',
            },
        ),
    ]
