# Generated by Django 4.2.30 on 2026-06-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0029_alter_batchrun_command_committeesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeesummary',
            name='activity_points',
            field=models.JSONField(default=list, help_text="Bulleted list (array of strings) of the committee's recent work, each citing representative bills."),
        ),
        migrations.AddField(
            model_name='committeesummary',
            name='scope_points',
            field=models.JSONField(default=list, help_text='Bulleted list (array of strings) of what the committee oversees — its departments and policy areas.'),
        ),
        migrations.AlterField(
            model_name='committeesummary',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Plain-text join of the bullet lists — a fallback for search / non-UI consumers. The UI renders scope_points + activity_points as lists.'),
        ),
    ]
