# Generated by Django 4.2.30 on 2026-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattle_app', '0030_committeesummary_activity_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeesummary',
            name='scope_intro',
            field=models.TextField(blank=True, default='', help_text='1-2 sentence lead-in shown above the scope bullets.'),
        ),
    ]
